### ISSUE TITLE
Fails to correctly detect daemon startup

### ISSUE THREAD

**Issue by goetzk** [ANXS/postgresql#111]
I just realised as part of filing #110 that ansible isn't correctly detecting the daemon failed to start.

```
TASK: [ANXS.postgresql | PostgreSQL | Create folder for additional configuration files] *** 
ok: [192.168.56.101]

TASK: [ANXS.postgresql | PostgreSQL | Restart PostgreSQL] ********************* 
changed: [192.168.56.101]

TASK: [ANXS.postgresql | PostgreSQL | Ensure PostgreSQL is running] *********** 
ok: [192.168.56.101]

TASK: [ANXS.postgresql | PostgreSQL | Make sure the PostgreSQL users are present] *** 
failed: [192.168.56.101] => (item={'encrypted': False, 'name': db_user', 'pass': u''}) => {"failed": true, "item": {"encrypted": false, "name": "db_user", "pass": ""}}
msg: unable to connect to database: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

**Comment by jesselang** [comment]
Does the socket file exist in /var/run/postgresql? I've found psql to expect the socket in a specific place, based on how it was compiled.

**Comment by goetzk** [comment]
Once running the socket appears in the correct directory. I suspect it was the task to start postgres that failed.

**Comment by TheBronx** [comment]
I faced this problem too.
PostgreSQL could not start because some files were owned by a different user.

That was because the variable "postgresql_admin_user" was set to "root" instead of "postgres":  
`postgresql_admin_user: "postgres"`

It is better not to change this variable I think...

**Comment by jlozadad** [comment]
is this still a problem?

**Comment by goetzk** [comment]
I'm not in a position to check at the moment i'm afraid. If you are looking to clean up issues I won't object to it being resolved.

thanks
kk

**Comment by jonfer** [comment]
@jlozadad yeah, I still have this problem

**Comment by jlozadad** [comment]
OK ty let us know if it comes up again. This can be closed.
