### ISSUE TITLE
Tests against CentOS hosts within travis 

### ISSUE THREAD

**Issue by farridav** [ANXS/postgresql#115]
We now have support for running against CentOS hosts within this role, but it needs manual testing in a VM or similar.. we have travis tests for the role (both integrity and idempotence) but they run against an ubuntu host, It would be great to get some test runs in against CentOS, perhaps with containers...

Useful links
- [Docker support within travis](https://docs.travis-ci.com/user/docker/)
- [Ansible blog post on docker/ansible usage](http://www.ansible.com/2014/02/12/installing-and-building-docker-with-ansible)

**Comment by portenez** [comment]
I just ran this role against my CentosVM using vagrant.. sorry no travis. and it fails :(

```
TASK: [ANXS.postgresql | PostgreSQL | Make sure the CA certificates are available] *** 
failed: [default] => {"cmd": "apt-get update '&&' apt-get install python-apt -y -q", "failed": true, "rc": 127}
stderr: /bin/sh: apt-get: command not found

msg: /bin/sh: apt-get: command not found

FATAL: all hosts have already failed -- aborting
```

looks like it's trying to use apt when in cent-os.

**Comment by farridav** [comment]
Yes, there is a PR up for this https://github.com/ANXS/postgresql/pull/119 which I've just merged in to master, I'm hoping to get some time either this week or this weekend to look at travis builds for both `ubuntu` and `centos` hosts,,, I will also be trying to figure out how I was able to get a successful `centos` build without hitting this error :)
