### ISSUE TITLE
Doesn't work on Centos 6.5

### ISSUE THREAD

**Issue by portenez** [ANXS/postgresql#118]
I ran the role against a centos vagrant, and didn't work. Looks like it's using **apt** in centos :(

```
TASK: [ANXS.postgresql | PostgreSQL | Make sure the CA certificates are available] *** 
failed: [default] => {"cmd": "apt-get update '&&' apt-get install python-apt -y -q", "failed": true, "rc": 127}
stderr: /bin/sh: apt-get: command not found

msg: /bin/sh: apt-get: command not found

FATAL: all hosts have already failed -- aborting
```

**Comment by portenez** [comment]
Ah btw, I got it directly from galaxy, not from the github repo.

**Comment by jesselang** [comment]
CentOS support is a recent addition. I'm guessing the version available from ansible-galaxy doesn't include CentOS support.

**Comment by farridav** [comment]
@portenez please let me know if this issue is now resolved with https://github.com/ANXS/postgresql/pull/119 merged in

**Comment by portenez** [comment]
Is it already on galaxy? or should I clone the repo? I'll give it a try as soon as I have a chance.

**Comment by jesselang** [comment]
I think you'll have to clone the repo. It doesn't look like galaxy has the latest.

**Comment by farridav** [comment]
I think we will need to create a new tag for this to get pulled in... will get this done today..

**Comment by farridav** [comment]
I have made a new tag for another feature, and manually re-imported the repo in ansbile galaxy.. after a quick test it appears to be pulling in the new tag with the fix in it... shout if you have any issues, if not.. feel free to close this

**Comment by portenez** [comment]
I just re-tried this, and although the role is no longer trying to use apt in centos, there's another error. I'm trying this with Vagrant:

TASK: [ANXS.postgresql | PostgreSQL | Initialize the database | RedHat] ******* 
fatal: [default] => Missing become password

FATAL: all hosts have already failed -- aborting

The thing is that with vagrant I usually don't need to provide a become password. I tried this role in combination with other roles, and I only see this error when running this role.

**Comment by farridav** [comment]
I have set my box to be `chef/centos5.5` and run `vagrant up`, and it provisions correctly, also subsequent `vagrant provision` and `ansible-playbook tests/playbook.yml -i vagrant-inventory` commands complete successfully.. do you have a branch I can check out with the commands you are running ?

**Comment by portenez** [comment]
Hi, thanks! 

 I'll create a gist with a sample playbook as soon as I have a chance, and I'll check the issue you're mentioning thanks.

**Comment by portenez** [comment]
Vagrant file:
https://gist.github.com/portenez/049c3a92bbff8950ba32

postgres.yml
https://gist.github.com/portenez/7ecfd152ecae695ea4d1

**Comment by portenez** [comment]
Ok, I found something.  If I change the box from "centos/6.5" to "nrel/CentOS-6.5-x86_64" then everything works fine. 

I'm ok with this solution (just changing the box), so I can close the issue now. Would you like me to?

**Comment by farridav** [comment]
Yeah if you could that'd be great.. I don't think we have issues running on centos 6.5.. Providing the user can sudo without a TTY :)

**Comment by portenez** [comment]
closing. Thanks!
