### ISSUE TITLE
update meta to list CentOS as supported os

### ISSUE THREAD

**Issue by kostyrev** [ANXS/postgresql#141]
I've stumbled upon this role just accidently. It's not ok. The world should know there's another role that may configure postgresql on CentOS.
If CentOS support is ready of course.
I didn't test it 'cause I'm using another role.

**Comment by farridav** [comment]
Hi @kostytreeva where this role does run as expected on centos, im in the process of getting a docker based travis test in, as soon as that is done, I will update the meta.yml file .. Just trying to find the time to finish up :)

**Comment by kostyrevaa** [comment]
np, the world can wait

**Comment by njbooher** [comment]
The release number is currently hardcoded in the [yum package URL](https://github.com/ANXS/postgresql/blob/76af2317bad800d6186db0bd84669e6902b5a1b8/defaults/main.yml#L674). Not every postgresql version has a release 2 package available in the repo.

**Comment by UnderGreen** [comment]
@gclough meta does not contain information about Centos-based OS compatibility. ¯\_(ツ)_/¯

**Comment by gclough** [comment]
@kostyrev ... if there is another decent Ansible role for PostgreSQL on CentOS, could you point me to it?  If things have already been developed elsewhere, then it doesn't make sense for me to re-work them here.

I've not found anything that's nearly as complete as `ANXS.postgresql`... but I'd be happy to find out if I've missed something better.

**Comment by kostyrev** [comment]
@gclough I was using [this](https://github.com/Open-Future-Belgium/PostgreSQL) one

**Comment by gclough** [comment]
Thanks @kostyrev .  I've had a quick look, and hopefully ANXS.postgresql will now do everything that one does, and more.

If there's something missing, then please open an issue, and tag me so I can take a look.

**Comment by jlozadad** [comment]
I would say this project is more active, supports more distro and does more best practice.

**Comment by kostyrev** [comment]
I'm not promoting that one. I've just answered what was a good fit for *my* needs at the time.

**Comment by gclough** [comment]
Indeed.  I asked, just so I could do a comparison and make sure there weren't any gaps in this one.  If you know of anything missing, please let us know by raising an issue.
