### ISSUE TITLE
Ansible v2 Deprecation Warning

### ISSUE THREAD

**Issue by pabse** [ANXS/postgresql#143]
With ansible version 2.0.0.2 I get the following deprecation warning:
```
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

This should be just a search&replace and easily to fix.

**Comment by clonedagain** [comment]
I think https://github.com/ANXS/postgresql/pull/146 fixes that, can you please review it?

**Comment by pabse** [comment]
Yes that does exactly that. That was fast. Thank you!

**Comment by clonedagain** [comment]
hehe it was posted a few days ago, don't thank me I'm only the messenger.

**Comment by farridav** [comment]
Closing as resolved, please feel free to re-open if you have further issues :)
