### ISSUE TITLE
Why isn't 1.3.0 on galaxy

### ISSUE THREAD

**Issue by iblazevic** [ANXS/postgresql#148]
We are experiencing some errors with upgrade to ansible 2 and those seem to be fixed in 1.3.0 release.

Why isn't that release available on galaxy?

**Comment by farridav** [comment]
Ansible galaxy seems to be playing up at the moment, it should automatically import roles when a new tag has been made, but it isnt.. Im having a similar issue with our nginx role.. ansible galaxy is not picking up the latest tag, I've even manually triggered an import, to no avail.. Im trying to look into this.. in the meantime, you can use github links in you requirements.yml, e.g http://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files

**Comment by iblazevic** [comment]
Thank you for the answer.

I'll leave issue closing to you, whether now or wait until its really published.

Thanks again

**Comment by farridav** [comment]
I've managed to get ansible galaxy sorted out and 1.4.0 is now available with full ansible 2 support, thanks to @jesselang :)
