### ISSUE TITLE
`fatal: [pg-1] => Missing become password` on backports-debian-7 (Google Compute) w/ Ansible 1.9.4

### ISSUE THREAD

**Issue by kevinschumacher** [ANXS/postgresql#154]
Running Debian 7 (specifically: `backports-debian-7` image on Google Cloud Platform/Compute Engine), I hit the following error for any tasks which try to `become` the `postgresql_admin_user` (**not** changed from the default value of `postgres`).

e.g.,:
- PostgreSQL | Reset the cluster - drop the existing one | Debian
- PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale) | Debian

fatal: [pg-1] => Missing become password

I am trying to install postgres 9.4 if that makes a difference. 

If I SSH into the machine (after the postgres package has been installed), and try to `sudo su postgres`, I am able to do so. 

Not sure if this is an ansible problem, or if there's something else we can do in the playbook to make this issue go away. 

Ansible 1.9.4

edit: this is from source (up to date master branch), not installed from galaxy

**Comment by kevinschumacher** [comment]
It looks like I'm probably not the first person to notice this (though this post references Ubuntu 14.10
https://groups.google.com/forum/#!topic/ansible-project/S1moqCLu9Ls


This thread seems to suggest that this might be a configuration issue of specific distributions with Ansible

https://groups.google.com/forum/#!searchin/ansible-project/sudo_user$20missing$20password/ansible-project/mTjnGaBvQss/aTO2PcQbw-8J

It describes the situation I'm in perfectly, but not specific to this playbook. Unfortunately it doesn't provide any answers

**Comment by farridav** [comment]
It seems to suggest that running the postgres user task without privelige escalation, and allowing it to just use the login_user instead works.. Id love to see a failing test for this, but we don't build on Debian targets yet.. 

If your familiar with docker you can add a build to our Travis file, see centos and Ubuntu examples.. Failing that I can try and put some time aside for it.. Been wanting to add Debian..

**Comment by gclough** [comment]
We don't explicitly support Debian v7, but if you have some ideas on what to do then we'd appreciate a Pull Request to fix it.

If it's no longer a problem, can you close it?

**Comment by UnderGreen** [comment]
Debian 7 reached EOL.  I'm going to close this issue.
