### ISSUE TITLE
Different postgresql data directory setup

### ISSUE THREAD

**Issue by twistsm** [ANXS/postgresql#157]
I've found strange situation with default data dir changing after initial setup:

How to reproduce:

Initially, we have  postgresql_data_directory started from "/var/lib"

```
postgresql_data_directory: "/var/lib/{{ postgresql_varlib_directory_name }}/{{postgresql_version}}/{{postgresql_cluster_name}}"
```

But I want to have my database files in another volume, "/data" for example. So I simply change the data directory. And then it fails to start on Debian systems, because of strange combination of following params:

```
# I missed this parameted first time, so it is false.
postgresql_cluster_reset: false

# and piece from configure.yml
- name: PostgreSQL | Reset the cluster - drop the existing one | Debian
  shell: pg_dropcluster --stop {{ postgresql_version }} {{ postgresql_cluster_name }}
  become: yes 
  become_user: "{{ postgresql_service_user }}"
  when: ansible_os_family == "Debian" and postgresql_cluster_reset and pgdata_dir_exist.changed

- name: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale) | Debian
  shell: >
    pg_createcluster --start --locale {{ postgresql_locale }}
    -e {{ postgresql_encoding }} -d {{ postgresql_data_directory }}
    {{ postgresql_version }} {{ postgresql_cluster_name }}
  become: yes 
  become_user: "{{ postgresql_service_user }}"
  when: ansible_os_family == "Debian" and postgresql_cluster_reset and pgdata_dir_exist.changed
```

My data dir changed, but postgresql_cluster_reset = false. Then I found and swithed `postgresql_cluster_reset` to `true`. And now it skips this steps because `pgdata_dir_exist.changed` never fired again :-)

I know, it is dumb situation, but maybe it's enough to have one explicit param `postgresql_cluster_reset` here to reset cluster?

Thanks, and sorry for my grammar. Anyway - this playbook very helpful and cool, thank you.

**Comment by easyecho** [comment]
@twistsm not a strange situation at all.  You can see this pull request #36 seems related -- I addressed it differently in my fork https://github.com/easyecho/ansible-role-postgresql which could probably be improved as I believe it restarts postgresql too often (which isn't a big deal in my use).

**Comment by skolsuper** [comment]
+1, I am also having this problem.

**Comment by dpetukhov** [comment]
I have another problem with this. I can't change locale if database cluster was created with wrong locale.

**Comment by raarts** [comment]
+1, I've got this problem too.

**Comment by jesselang** [comment]
@briandbecker will you be making a pull request available?

**Comment by briandbecker** [comment]
@jesselang -- my changes need work as they currently restart the server on every run.  I'll see if I can clean them up for a PR...

**Comment by jesselang** [comment]
@briandbecker, sounds great. Feel free to make an incomplete PR against https://github.com/jesselang/postgresql/tree/incoming . I'll be happy to work on the restarts.
