### ISSUE TITLE
Asking password when creating database

### ISSUE THREAD

**Issue by lihan** [ANXS/postgresql#167]
The task will fail if swich user to {{postgres_admin_user}}, any idea?

``
become: yes

become_user: "{{postgresql_admin_user}}"
``

failed: [xxx.xxx.xxx.xxx] => (item={u'owner': u'postgres_db_user', u'citext': True, u'name': u'db_name', u'uuid_ossp': True, u'hstore': False}) => {"failed": true, "invocation": {"module_name": "postgresql_db"}, "item": {"citext": true, "hstore": true, "name": "db_name", "owner": "postgres_db_user", "uuid_ossp": true}, "module_stderr": "", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by jesselang** [comment]
Please try running the role as the `root` user using `become: yes` when running the role.

**Comment by shahinism** [comment]
Related issue https://github.com/ansible/ansible/issues/16048.
When we are not using root as `remote_user` (eg. disabled ssh to `root` user for security reasons) then `become` will try to access `postgres` user using `sudo` and if your user is not privileged enough, it needs a password. 

Adding following line with your become_user name will solve the issue:

```
MY_BECOME_USER ALL=(ALL:ALL) NOPASSWD:ALL
```
