### ISSUE TITLE
Maintained fork?

### ISSUE THREAD

**Issue by jadams5** [ANXS/postgresql#170]
Is this repo dead? There's been unmerged pull requests out there for a couple months and the module is broken against the current version of Ansible.

**Comment by farridav** [comment]
The repo is maintained, but theres seems to be a drop in maintainer availability at the moment (myself included, due to personal circumstances) Ill give the other maintainers a nudge to see if we can get back on top of this, I hope to be able to put some time back into this from June onwards..

**Comment by jadams5** [comment]
Thanks for the update!

**Comment by jeffwidman** [comment]
@farridav if you need help, I'd be happy to help maintain. I'm a collaborator on a number of open source projects including `flask` and `jinja2`, and also maintain several of my own Ansible roles: https://github.com/search?q=user%3Ajeffwidman+ansible

**Comment by farridav** [comment]
Sure, feel free to set PRS against this repo and @ me, I'll keep an eye out for your handle.. Meanwhile I'll speak to the organisation owner and see about extending the maintainers list
