### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jeffwidman** [ANXS/postgresql#177]
Would love to see a new release incorporating https://github.com/ANXS/postgresql/pull/165 so that I don't have deprecation warnings everywhere

**Comment by otakup0pe** [comment]
good point, will do so later today

**Comment by otakup0pe** [comment]
1.5.0 should hit galaxy soon!

**Comment by jeffwidman** [comment]
BTW, in the future, you might consider tagging releases as `1.5.0` rather than `v1.5.0` because it makes for a cleaner Ansible `requirements.yml`:

    - src: ANXS.postgresql
      version: v1.5.0

vs

    - src: ANXS.postgresql
      version: 1.5.0

**Comment by otakup0pe** [comment]
I'll ask around. I just kept cargo culting that when I started helping on these roles...
