### ISSUE TITLE
There is no template for Centos6 service

### ISSUE THREAD

**Issue by jeanpaulmanjarres-payulatam** [ANXS/postgresql#182]
Hi, 
i've been trying to use this role and it works great. But if i need to change de Data path, the role will not work on Centos6. The problem is that this role installs a service file for postgres in a "systemd" format, so the reference to the selected data dir is written there. But Centos6 will use a service script in /etc/init.d/ path, and the only script that exists is the default installed by yum. The Data dir is not updated with the selected in the role vars.

Is there any plan to support this?

**Comment by jlozadad** [comment]
is this still an issue?
