### ISSUE TITLE
Postgis installation fails on Ubuntu/Xenial

### ISSUE THREAD

**Issue by postfalk** [ANXS/postgresql#183]
Install attempts installation of libgeos-c1 which seems to be replaced by libgeos-c1v5.

**Comment by mvsantoss** [comment]
+1

**Comment by thbar** [comment]
Still the case today. I hardcoded a local change with `libgeos-c1v5`. I wonder if we need a conditional something here, or maybe a variable?

**Comment by moviedo** [comment]
Added pull request for this issue. Tested the fix locally with the provided project Vagrantfile and Ubuntu/Xenial64 box. https://github.com/ANXS/postgresql/pull/231

**Comment by rraub** [comment]
duplicate issue #159
