### ISSUE TITLE
Service not starting in LXD container status=206/OOM_ADJUST

### ISSUE THREAD

**Issue by indispeq** [ANXS/postgresql#187]
Hello,

thank you for the great role, it has helped us tremendously in our work. I noticed an error that happens in an LXD container on debian Jessie: the service will not start up and gives the following error:

```
root@postgresql:~# systemctl status postgresql@9.4-main.service                                                            
● postgresql@9.4-main.service - PostgreSQL Cluster 9.4-main
   Loaded: loaded (/lib/systemd/system/postgresql@.service; disabled)
   Active: failed (Result: exit-code) since Fri 2016-07-01 18:37:17 UTC; 6s ago
  Process: 7761 ExecStart=postgresql@%i --skip-systemctl-redirect %i start (code=exited, status=206/OOM_ADJUST)

Jul 01 18:37:17 postgresql systemd[1]: postgresql@9.4-main.service: control process exited, code=exited status=206
Jul 01 18:37:17 postgresql systemd[1]: Failed to start PostgreSQL Cluster 9.4-main.
Jul 01 18:37:17 postgresql systemd[1]: Unit postgresql@9.4-main.service entered failed state.
```

I was able to get around this by editing `/lib/systemd/system/postgresql@.service`
and commenting out the line:

```
OOMScoreAdjust=-900
```

After a `systemctl daemon-reload` the service started.

I am thinking maybe find a way to determine that the machine is in an LXD container and make this modification (if indeed it is a valid one). I can test on other LXD containers of other OS versions too. In a regular LXC container this behavior does not happen.

Let me know if I can furnish more info.

**Comment by gclough** [comment]
Is this still a problem?  The role is tested automatically on Debian 8 and 9?
