### ISSUE TITLE
Add me as a contributor

### ISSUE THREAD

**Issue by UnderGreen** [ANXS/postgresql#192]
I am Ansible modules developer and roles creator. I want to improve this role and don't want to wait when you will merge PR's. You have open a lot of PR's and issues. I can help to decrease this values.

**Comment by otakup0pe** [comment]
Let's do this! Can you come onto the Gitter channel so we can talk?

**Comment by UnderGreen** [comment]
Where I can find information about Gitter channel(s)?

**Comment by pjan** [comment]
[here](https://gitter.im/ANXS)

**Comment by UnderGreen** [comment]
I did't see how I can add myself to this channel.

**Comment by pjan** [comment]
Invitation to the group is [here](https://github.com/ANXS). You should first accept that one.

**Comment by otakup0pe** [comment]
It was fun while it lasted, @UnderGreen 💖
