### ISSUE TITLE
postgis instalation failure on CentOS

### ISSUE THREAD

**Issue by artworx** [ANXS/postgresql#194]
There seems to be no support for CentOS in [extensions/postgis.yml](https://github.com/ANXS/postgresql/blob/v1.6.2/tasks/extensions/postgis.yml)

**Comment by taybin** [comment]
Just ran into this myself.

**Comment by gclough** [comment]
Fixed by #310 .  Once it's merged, then can we close this?

**Comment by jlozadad** [comment]
closing this since we have other tickets about postgis and a PR that is being tested.
