### ISSUE TITLE
On RedHat pgtune is incompatible with PostgreSQL 9.5 

### ISSUE THREAD

**Issue by mjuenema** [ANXS/postgresql#201]
On RedHat family systems the pgtune tool will create configurations that are incompatible with PostgreSQL 9.5 as the checkpoint_segments parameter has been renamed to [min|max]_wal_segments.  See also https://github.com/le0pard/pgtune/issues/2.
The best work-around would probably be to not run pgtune if the PostgreSQL version is incompatible.

**Comment by dmishh** [comment]
Same on Ubuntu

**Comment by gclough** [comment]
It seems that the original `pgtune` has been abandonded... but I did find a new project here:

https://github.com/le0pard/pgtune

It's not quite the same, so I don't know how much work it will be use that instead, or even if it's possible.

**Comment by gclough** [comment]
I'm working on #301 , which should achieve the goals of pgtune... but purely in Ansible, and is compatible with later versions of PostgreSQL.

It's not 100% tested yet, as I need to benchmark the suggestions on different server sizes.
