### ISSUE TITLE
Fails on earlier PostgreSQLs

### ISSUE THREAD

**Issue by scottanderson42** [ANXS/postgresql#21]
I'm installing a 9.1 installation on an older Ubuntu machine. The following postgresql.conf config parameters are invalid but are included anyways:

#unix_socket_directories = '{{postgresql_unix_socket_directories|join(',')}}'
#unix_socket_group       = '{{postgresql_unix_socket_group}}'
#unix_socket_permissions = {{postgresql_unix_socket_permissions}}

#ssl_cert_file           = '{{postgresql_ssl_cert_file}}'
#ssl_key_file            = '{{postgresql_ssl_key_file}}'
#ssl_ca_file             = '{{postgresql_ssl_ca_file}}'
#ssl_crl_file            = '{{postgresql_ssl_crl_file}}'

#temp_file_limit = {{postgresql_temp_file_limit}}

#wal_sender_timeout = {{postgresql_wal_sender_timeout}}

#wal_receiver_timeout = {{postgresql_wal_receiver_timeout}}

#enable_indexonlyscan = {{'on' if postgresql_enable_indexonlyscan else 'off'}}

#event_source             = '{{postgresql_event_source}}'

#track_io_timing           = {{'on' if postgresql_track_io_timing else 'off'}}

#lock_timeout                   = {{postgresql_lock_timeout}}

Additionally, it's looking for the postgis package in the wrong place on Ubuntu 13.04:

Does not work on 13.04
    - "postgresql-{{postgresql_version}}-postgis-{{postgresql_ext_postgis_version}}"

Does work
    - "postgresql-{{postgresql_version}}-postgis"

**Comment by rud** [comment]
@scottanderson42 this seems like a good time to fork and adjust your own copy to taste. Not sure it makes sense to generate configurations for older versions of the software, but that may just be me?

**Comment by tehranian** [comment]
It seems to me that one could use Ansible's `version_compare()` filter in the `postgresql.conf.j2` template and conditionally not put the offending configuration directives for older versions of PostgreSQL.

http://docs.ansible.com/playbooks_variables.html#version-comparison-filters

**Comment by rud** [comment]
Always an option, sure. There's a cost/benefit tradeoff in that, though, plus more permutations to test and verify going forward. Just thought I'd chime in on a months old issue is all.

**Comment by sebalix** [comment]
If Ansible is used to bootstrap a system that's ok to forget old versions of PostgreSQL. But if the playbooks are run from time to time on hosts running different versions of Pg, this is nice to support at least the last versions. A workaround would be to checkout this role several times on different commits following the versions we need to support... but it's a bit ugly, I think.

**Comment by clonedagain** [comment]
@rud since there's a "version" option, users expect several versions to be installable. If only some versions are, it must be clear and not fail with an obscure error message.

@sebalix there is still enough servers deployed in production with older versions to make it a valid use case IMHO. When an old PG is part of a officially supported stack (ie. Odoo v7 officially targets PG 9.1) and PG works well enough, operators will be reluctant to upgrade.

**Comment by sebalix** [comment]
We are in the same case, we manage PostgreSQL from version 9.1 to 9.4 (and some 8.X too, but it's not a problem if we don't support them via Ansible).

**Comment by jean** [comment]
Just starting out with this recipe and PostgreSQL 9.2, `LOG:  unrecognized configuration parameter "unix_socket_directories" in file "/etc/postgresql/9.2/main/postgresql.conf" line 57` etc ...

**Comment by rud** [comment]
I think a PR to fix this is welcome :star2:

**Comment by otakup0pe** [comment]
We would almost certainly merge an PR around a good implementation of this fix, such as is being discussed.

**Comment by sebalix** [comment]
It has already be done for PostgreSQL 9.3 and 9.4: https://github.com/ANXS/postgresql/pull/66
We just need to add postgresql.conf files related to the 9.2 version and update available options:
  - add the upstream `postgresql.conf-9.2.orig` (from the Debian package for instance)
  - make a diff between the `9.3.orig` and `9.2.orig`
  - copy `postgresql.conf-9.3.j2` from `postgresql.conf-9.2.j2` and adapt it following the previous diff
  - update `default/main.yml`
  - update `.travis.yml` to test this version

I can do it if you want.

**Comment by sebalix** [comment]
I started to work on the support of 9.1 and 9.2 versions. There is some conflicts with the PostgreSQL pre-installed by Travis, I try to fix them and I will make a PR.

**Comment by soupdiver** [comment]
@sebalix Thanks man!
