### ISSUE TITLE
Compatibility with Ansible 2.1

### ISSUE THREAD

**Issue by unicell** [ANXS/postgresql#210]
Task fail with Ansible 2.1 due to https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user

> TASK [ANXS.postgresql : PostgreSQL | Make sure the PostgreSQL users are present] ***
> [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_users}}').
> This feature will be removed in a future release. Deprecation warnings can be disabled by setting
> deprecation_warnings=False in ansible.cfg.
> fatal: [<hostname>]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}

**Comment by tetor** [comment]
I have same issue. +1

**Comment by davidak** [comment]
I don't have this error with Ansible 2.2.

**Comment by IvikGH** [comment]
I have this issue with Ansible 2.2.0.0.
It appears only when I setup Postgres on [Scaleway](https://cloud.scaleway.com) VPS.
Error **doesn't** appear when I setup Postgres on [DigitalOcean](https://cloud.digitalocean.com) VPS.

**Comment by otakup0pe** [comment]
Is this still a problem or can we close it

**Comment by acrewdson** [comment]
@otakup0pe It's still a problem in Ansible 2.3.x -- at least in some situations.

**Comment by jlozadad** [comment]
is this still a problem? latest version of ansible is in 2.4.x and should be using that version.

**Comment by patsevanton** [comment]
The workaround for me was to install acl
