### ISSUE TITLE
Should we use no_log for postgresql_user?

### ISSUE THREAD

**Issue by thbar** [ANXS/postgresql#215]
Today I noticed that when using a `password: {{ key }}` (with the key stored encrypted via ansible-vault), the password will show up in the log.

As [seen here](https://github.com/Open-Future-Belgium/PostgreSQL/pull/9), maybe it would be a good idea to specify `no_log` here, like is done in `ANXS.generic-users`?

**Comment by otakup0pe** [comment]
Haha wow yeah we should.

**Comment by thbar** [comment]
@otakup0pe I have little knowledge of how tweaking this could impact anything, but I could issue a PR.

Is it worth submitting a PR for? Thanks!

**Comment by otakup0pe** [comment]
Absolutely worthy of a PR!

**Comment by thbar** [comment]
@otakup0pe PR issued at #275.

Re: tests, I wonder if adding tests with [inspec](https://www.inspec.io) or his older brother [serverspec](http://serverspec.org) could maybe ease both contributions & maintenance.

Just a though!
