### ISSUE TITLE
"Failed to restart postgresql.service: Interactive authentication required"

### ISSUE THREAD

**Issue by thbar** [ANXS/postgresql#217]
Using v1.5.0 from Galaxy, I get this error (but not all the time - maybe because the handler is not run, not sure).

```
RUNNING HANDLER [ANXS.postgresql : restart postgresql] *************************
fatal: [192.168.33.10]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service postgresql: Failed to restart postgresql.service: Interactive authentication required.\nSee system logs and 'systemctl status postgresql.service' for details.\n"}
```

I'm on ansible 2.2.0.

**Comment by thbar** [comment]
Potentially similar to [ansible-redis/issues/137](https://github.com/DavidWittman/ansible-redis/issues/137)

**Comment by thbar** [comment]
This could indeed be a [bug in ansible 2.2](https://github.com/DavidWittman/ansible-redis/issues/137#issuecomment-268682208), to be verified.

**Comment by jlozadad** [comment]
this shouldn be an issue since everyone should be using 2.4
