### ISSUE TITLE
Compatibility with Ansible 2.2 is broken

### ISSUE THREAD

**Issue by armab** [ANXS/postgresql#218]
Ansible `2.2` is out, and here is where it fails with currently latest ANXS.postgresql `v1.6.2`:

![](https://i.imgur.com/q1QRy1b.png)

FYI.

**Comment by thom-nic** [comment]
From [this SO answer](http://stackoverflow.com/a/33303940/213983) it would seem the `with_items` lines should be changed to 
```
with_items: postgresql_users
```
the same issue might also be present [here](https://github.com/ANXS/postgresql/blob/475e292f505be0d99cc20e2517043c30353a092c/tasks/databases.yml#L38) as well

**Comment by clonedagain** [comment]
@thom-nic I don't think so, Ansible 2.2 will treat `postgresql_users` as a plain string if you do that.

**Comment by thom-nic** [comment]
@clonedagain actually I think you're right - ansible is confusing in that it interprets some values (e.g. `when:` but others it always treats the value as a string.

**Comment by thom-nic** [comment]
This error would occur if you did something like this:
```
vars:
  postgresql_users:
    - 'bob'
```
(error indicates it's got a string but it's expecting a dict with `name` attr)

however mine (and assuming @armab ) looks like this:
```
vars:
  postgresql_users:
    - name: asdf
      pass: secret
      encrypted: yes       
```
... for whatever reason it works fine in Ansible 2.1.2 but not 2.2....

**Comment by clonedagain** [comment]
@thom-nic that's because the feature was deprecated in 2.1 and then removed from 2.2. I had to fix this all over my own playbooks...

**Comment by thom-nic** [comment]
Which feature exactly? I'm sure you don't mean `with_items` was deprecated.  

What did you do to fix it?

**Comment by clonedagain** [comment]
@thom-nic Sorry I was unspecific: https://docs.ansible.com/ansible/porting_guide_2.0.html#deprecated states: "Bare variables in with_ loops should instead use the “{{var}}” syntax, which helps eliminate ambiguity."

One example here: https://github.com/bcoca/ansible-oracle_java7-role/pull/9/files

**Comment by thom-nic** [comment]
@clonedagain ok thanks, yes I was aware of that particular issue.  Looks like that has been fixed for a while in this repo: https://github.com/ANXS/postgresql/commit/d28da5a52597f037fbca8bbac8e328d25eed72bc 

I will verify that the version I'm using locally does in fact have that fix.

**Comment by thom-nic** [comment]
There's surprisingly no record of the installed version when you install a galaxy role (oops!) however deleting the role from `.galaxy/` and reinstalling fixed the issue, I had to do 
```
grep with_items .galaxy/ANXS.postgresql/tasks/users.yml
```
to verify.

So it would seem this *has* been fixed, you just need to reinstall the role to get it.

**Comment by armab** [comment]
@thom-nic You're right, I just re-tried on a clean box and it worked.
Sorry guys for opening this, I really messed somewhere with versions or caching :disappointed: 

Confirming that latest `1.6.2` `ANXS.postgresql` worked OK with Ansible `2.2`.
