### ISSUE TITLE
How to upgrade postgres with the playbook?

### ISSUE THREAD

**Issue by thbar** [ANXS/postgresql#219]
I've recently used this playbook to install postgres 9.5 for a simple deployment (mono-instance, low scale), kudos for the great work!

[9.6 support](#212) is soon to be merged. I searched tips on how to handle such an upgrade using the playbook, and thought I'd write down what I found, in hope we can maybe create a readme section (at least for simple cases).

I found the following useful elements :
- [`postgresql_service_enabled`](https://github.com/ANXS/postgresql/blob/master/defaults/main.yml#L21) could I guess be used to switch off the database while at 9.5.
- [issue #101](https://github.com/ANXS/postgresql/issues/101) seems to hint that 2 versions will be installed at once on the same port by default
- for simple deployments, an automated call to [pg_upgrade](https://www.postgresql.org/docs/9.6/static/pgupgrade.html) could do the trick

I suppose we could have an `postgresql_run_pg_upgrade` type of variable, which could enforce the shutdown of the database, then the run of `pg_upgrade` etc.

If anyone already conducted such an upgrade in a semi or full automated fashion, please share more bits so we can group these in a readme section. Thanks!

**Comment by lhoss** [comment]
nice initiative 👍 
once upgrading from 9.5 to 9.6 gets a priority for my team, happy to contribute, including making it work for  (docker)containerized postgres deployments, that we added in 
https://github.com/ANXS/postgresql/pull/213  (hopefully getting merged at some point)
