### ISSUE TITLE
Error on "Add PostgreSQL repository"

### ISSUE THREAD

**Issue by IvikGH** [ANXS/postgresql#221]
fatal: [138.68.103.222]: FAILED! => {"failed": true, "msg": "The conditional check 'postgresql_apt_repository' failed. The error was: expected token 'end of statement block', got 'http'
  line 1

  The error appears to have been in '/etc/ansible/roles/ANXS.postgresql/tasks/install.yml': line 17, column 3, but may
  be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: PostgreSQL | Add PostgreSQL repository
  ^ here
  "}

**Comment by IvikGH** [comment]
This error appeared today.
Yesterday everything worked fine.

**Comment by yethee** [comment]
This role is not compatible with Ansible >= 2.1.4.0.

**Comment by IvikGH** [comment]
Thanks a lot.
It **works perfectly for 2.2.0.0** but `not for 2.2.1.0`

**Comment by jeffwidman** [comment]
Thanks for reporting, just ran into this myself

**Comment by Envek** [comment]
There is a workaround in https://github.com/ANXS/postgresql/issues/223#issuecomment-273805915
