### ISSUE TITLE
Vagrant up fails with error

### ISSUE THREAD

**Issue by IvikGH** [ANXS/postgresql#222]
/etc/ansible/roles/ANXS.postgresql $ sudo vagrant up
[sudo] password for ivik: 
Bringing machine 'anxs' up with 'virtualbox' provider...
==> anxs: Checking if box 'ubuntu/trusty64' is up to date...
==> anxs: Clearing any previously set network interfaces...
==> anxs: Preparing network interfaces based on configuration...
    anxs: Adapter 1: nat
    anxs: Adapter 2: hostonly
==> anxs: Forwarding ports...
    anxs: 22 (guest) => 2222 (host) (adapter 1)
==> anxs: Booting VM...
==> anxs: Waiting for machine to boot. This may take a few minutes...
    anxs: SSH address: 127.0.0.1:2222
    anxs: SSH username: vagrant
    anxs: SSH auth method: private key
    anxs: Warning: Remote connection disconnect. Retrying...
    anxs: Warning: Remote connection disconnect. Retrying...
==> anxs: Machine booted and ready!
==> anxs: Checking for guest additions in VM...
    anxs: The guest additions on this VM do not match the installed version of
    anxs: VirtualBox! In most cases this is fine, but in rare cases it can
    anxs: prevent things such as shared folders from working properly. If you see
    anxs: shared folder errors, please make sure the guest additions within the
    anxs: virtual machine match the version of VirtualBox you have installed on
    anxs: your host and reload your VM.
    anxs: 
    anxs: Guest Additions Version: 4.3.36
    anxs: VirtualBox Version: 5.1
==> anxs: Setting hostname...
==> anxs: Configuring and enabling network interfaces...
==> anxs: Mounting shared folders...
    anxs: /vagrant => /etc/ansible/roles/ANXS.postgresql
==> anxs: Running provisioner: ansible...
    anxs: Running ansible-playbook...
**ERROR! the role 'postgresql' was not found in /etc/ansible/roles/ANXS.postgresql/tests/roles:/etc/ansible/roles:/etc/ansible/roles/ANXS.postgresql/tests**

**The error appears to have been in '/etc/ansible/roles/ANXS.postgresql/tests/playbook.yml': line 9, column 7, but may**
**be elsewhere in the file depending on the exact syntax problem.**

**The offending line appears to be:**

  **roles:**
    **- postgresql**
      **^ here**

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by yethee** [comment]
What version of Ansible you use?

**Comment by IvikGH** [comment]
Version ansible 2.2.0.0 works properly.

**Comment by eugenevd** [comment]
I've had the same problem. 
Using ansible-galaxy install: ansible-galaxy install ANXS.postgresql
result in a directory named "ANXS.postgresql"
Yet the playbooks refer to the role as "postgresql" - renaming as such solved this issue for me.
(This caused warnings when doing vagrant commands, which was solved after 'vagrant destroy && vagrant up)

Not sure if this is the best approach though?
