### ISSUE TITLE
Role breaks with newer versions of ansible

### ISSUE THREAD

**Issue by rommsen** [ANXS/postgresql#223]
The reason is that there are "truthy" checks for string variables. For example this line https://github.com/ANXS/postgresql/blob/master/tasks/install.yml#L21 gives us
```
fatal: [testserver1]: FAILED! => {"failed": true, "msg": "The conditional check 'postgresql_apt_repository' failed. The error was: expected token 'end of statement block', got 'http'\n  line 1\n\nThe error appears to have been in '/home/roman/development/deployment/ansible/roles/vendor/ANXS.postgresql/tasks/install.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: PostgreSQL | Add PostgreSQL repository\n  ^ here\n"}
```

This breaks for us in ansible 2.2.0
See: https://github.com/ansible/ansible/issues/20392

**Comment by Freika** [comment]
Same problem here.

**Comment by MikeStankavich** [comment]
+1, I just added a comment to the upstream with a test case where I found that the conditional is attempting to evaluate the string.

For now I've changed `when: postgresql_apt_repository` to `when: postgresql_apt_repository | default('') != ''` as a workaround

**Comment by clonedagain** [comment]
I think ``|bool`` should be enough to make the condition evaluate to false when the string is empty.

**Comment by MikeStankavich** [comment]
Good point, definitely a cleaner workaround. Thanks for sharing that one.

**Comment by ticklemynausea** [comment]
Using the `| bool` workaround by @clonedagain fails for me:

```
TASK [ANXS.postgresql : PostgreSQL | Add PostgreSQL repository] ****************
task path: /etc/ansible/roles/ANXS.postgresql/tasks/install.yml:17
skipping: [exclusiph-api] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}
```

(patch I used: https://github.com/Musikki/postgresql/commit/d663a688c9a9f025198d4e809a4fe197e585c7e2)

It no longer throws an error, but the postgresql repository is not added, and therefore pgsql doesn't get installed.

Using the other hack by @MikeStankavich seems to work fine in adding the apt repository and getting pgsql installed.

Ansible version 2.2.1.0

**Comment by clonedagain** [comment]
@ticklemynausea you're right, I just checked and |bool is true only if the string is yes/no/true/false.
My bad.

**Comment by clonedagain** [comment]
I've updated my pull request to reflect the better fix exposed here (commit author respected).

**Comment by thom-nic** [comment]
Are releases still being pushed to Galaxy? I just tried to reinstall this role to get this fix but it appears the last version on https://galaxy.ansible.com/ANXS/postgresql/ is v1.5.

**Comment by fcanela** [comment]
I am facing the same issue than @thom-nic. Will new releases be pushed to ansible-galaxy?

**Comment by Dr8f** [comment]
@otakup0pe Can we have an update on this please?

**Comment by otakup0pe** [comment]
I'll get a release out for this!

Related; looking for additional maintainers to help out with the ANXS roles. Let me know if you have interest and (unlike my current state) time!
