### ISSUE TITLE
Yum install not working in last version.

### ISSUE THREAD

**Issue by insspb** [ANXS/postgresql#225]
I have several test platforms. When I install this role with ansible-galaxy all works fine. 
When I install this role with git clone last version I got this error:
```
fatal: [alfrescot1.local]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-.noarch.rpm, 'NoneType' object has no attribute 'read'"}
fatal: [alfrescot2.local]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://yum.postgresql.org/9.3/redhat/rhel-7-x86_64/pgdg-centos93-9.3-.noarch.rpm, 'NoneType' object has no attribute 'read'"}
```

I think something wrong with 88fdf0bb5473e0c77aa7c3d0fbf9b1b7f0e98d11

**Comment by jlozadad** [comment]
looks like pgdg-centos95-9.5-.noarch.rpm is not available on the repo anymore and the other is not either. if you search for them in http://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/ you won't get anything.

**Comment by jlozadad** [comment]
looks like this is fixed now and this can be closed.
