### ISSUE TITLE
postgresql_user_privileges: db: should not be optional in ansible

### ISSUE THREAD

**Issue by davidak** [ANXS/postgresql#233]
https://github.com/ANXS/postgresql/blob/master/tasks/users_privileges.yml#L6

```
failed: [db1] (item={u'priv': u'', u'role_attr_flags': u'LOGIN,REPLICATION', u'name': u'replication'}) => {"failed": true, "item": {"name": "replication", "priv": "", "role_attr_flags": "LOGIN,REPLICATION"}, "msg": "privileges require a database to be specified"}
```

**Comment by davidak** [comment]
Would you accept a PR for this?

**Comment by lhoss** [comment]
actually we do not have this issue ... and I just found WHY you got the issue 👍 
from above output I see, that you are providing a `priv` attribute, that though empty `''`, seems enough to require also the `db` parameter. 
Try to *omit*  `priv` completely, and it should work (does for us)!

**Comment by jlozadad** [comment]
Looks like this is not an issue anymore. It can be closed.
