### ISSUE TITLE
Custom data directory only works on redhat

### ISSUE THREAD

**Issue by macnibblet** [ANXS/postgresql#236]
I tried changing the data directory on a ubuntu install, and it failed miserably, read the playbook. only supported on redhat.

**Comment by briandbecker** [comment]
@macnibblet I had the same issue; I forked and got it working so feel free to take a look: https://github.com/briandbecker/ansible-role-postgresql

**Comment by merifri** [comment]
@macnibblet , what about [postgresql_cluster_reset](https://github.com/ANXS/postgresql/blob/master/defaults/main.yml#L24) variable? You can set it to `true` and cluster will be created in new `postgresql_data_directory` (if cluster exists, it will be dropped): 
https://github.com/ANXS/postgresql/blob/master/tasks/configure.yml#L36-L49

Tested on Debian and Ubuntu.

**Comment by corford** [comment]
@merifri Haven't tested but reading the source, I don't think setting postgresql_cluster_reset=true will drop an existing cluster. The task that drops the cluster checks for 'pgdata_dir_exist.changed' before running (which will be false if the data data directory already exists).

**Comment by corford** [comment]
@macnibblet it's supposed to be supported on Debian but I couldn't get it working on Ubuntu (xenial). Issue seems to be with pg_createcluster and pg_dropcluster commands in tasks/configure.yml. I've made a pull request with the fix that worked for me here: https://github.com/ANXS/postgresql/pull/237

**Comment by jlozadad** [comment]
is this still an issue?
