### ISSUE TITLE
ansible-lint fails

### ISSUE THREAD

**Issue by mrPsycho** [ANXS/postgresql#240]
tried to use your role with ansible-lint.
and..... was confused :)

[gitlab-runner@doit_build doit-ansible]$ ansible-lint *.yml
[ANSIBLE0013] Use shell only when shell functionality is required
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:36
Task/Handler: PostgreSQL | Reset the cluster - drop the existing one | Debian

[ANSIBLE0013] Use shell only when shell functionality is required
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:36
Task/Handler: PostgreSQL | Reset the cluster - drop the existing one | Debian

[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:36
Task/Handler: PostgreSQL | Reset the cluster - drop the existing one | Debian

[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:36
Task/Handler: PostgreSQL | Reset the cluster - drop the existing one | Debian

[ANSIBLE0013] Use shell only when shell functionality is required
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:42
Task/Handler: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale) | Debian

[ANSIBLE0013] Use shell only when shell functionality is required
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:42
Task/Handler: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale) | Debian

[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:42
Task/Handler: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale) | Debian

[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:42
Task/Handler: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale) | Debian

[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:57
Task/Handler: PostgreSQL | Initialize the database | RedHat

[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:57
Task/Handler: PostgreSQL | Initialize the database | RedHat

[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:161
Task/Handler: PostgreSQL | Restart PostgreSQL

[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/configure.yml:161
Task/Handler: PostgreSQL | Restart PostgreSQL

[ANSIBLE0011] All tasks should be named
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/main.yml:3
Task/Handler: include_vars {{ item }}

[ANSIBLE0011] All tasks should be named
/home/gitlab-runner/builds/f4ecf6c4/0/ok/doit-ansible/roles/ANXS.postgresql/tasks/main.yml:3
Task/Handler: include_vars {{ item }}

it is not critical, but would be great if it will pass.

**Comment by otakup0pe** [comment]
Pull requests welcome!

**Comment by jlozadad** [comment]
I know for some of this are false positive( for some of the shell output) but, when it comes to use the handler to restart a service then yes, it should use a handler.
