### ISSUE TITLE
any plans to write some docs? maybe examples?

### ISSUE THREAD

**Issue by mrPsycho** [ANXS/postgresql#241]
for example, i just struggled with 9.2 under centos 7.

and found, that playbook looks for socket in `/tmp` instead of `/var/run/postgresql`. 
also, would be nice to see any basic master-slave replication.

**Comment by AJamesPhillips** [comment]
@myPsycho [it's got some docs](https://github.com/ANXS/postgresql).  What example are you looking for, it sounds like master-slave?  It would be great if you submitted a PR with your setup once you have it up and running.

**Comment by otakup0pe** [comment]
Literally what @AJamesPhillips said.... Pull Requests welcome!

**Comment by jlozadad** [comment]
@mrPsycho I know this is specific to tower but, here is a good example of how to do it https://github.com/samdoran/ansible-role-postgresql-replication

**Comment by jlozadad** [comment]
This ticket can be closed.
