### ISSUE TITLE
Repo add fails in Ubuntu 16.10

### ISSUE THREAD

**Issue by MounirMesselmeni** [ANXS/postgresql#244]
TASK [ANXS.postgresql : PostgreSQL | Add PostgreSQL repository] ****************
fatal: [domain.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to domain.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Wjjeqf/ansible_module_apt_repository.py\", line 538, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Wjjeqf/ansible_module_apt_repository.py\", line 527, in main\r\n    cache.update()\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 464, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: E:The repository 'http://apt.postgresql.org/pub/repos/apt yakkety-pgdg Release' does not have a Release file.\r\n", "msg": "MODULE FAILURE"}

Server running Ubuntu 16.10, then apt update break until I remove the added source.

My current workaround is:
`postgresql_apt_repository: ''`

**Comment by AndreaFox93** [comment]
Same problem for me on 16.10, for now i've added ansible_distribution_release: xenial and all goes fine, i don't know if is good to do but i'm on a staging machine so it's only to install it.

On ubuntu 16.04 everything works fine!

**Comment by damien-roche** [comment]
For others, the `ansible_distribution_release` will need to go into both `defaults/main.yml` and `vars.yml`.

**Comment by ImTheDeveloper** [comment]
Worked for me also thanks!

**Comment by jlozadad** [comment]
is this still an issue?

**Comment by UnderGreen** [comment]
It can't be issue now. Ubuntu 16.10 reached EOL :smile:
