### ISSUE TITLE
initdb on Ubuntu

### ISSUE THREAD

**Issue by chadwilken** [ANXS/postgresql#249]
I’m trying to install on Ubuntu 14.04. When I run the playbook using this role it fails because the main directory is empty from what I can tell is the lack of calling initdb. I looked into the source code and see that it only calls that on RedHat. I want to avoid manually running any code of course. How can I get the installation to finish?

**Comment by gclough** [comment]
It should run `pg_createcluster` on Debian... which is a wrapper around `initdb`.  This is quite an old issue, so do I presume it's working for you?

**Comment by jlozadad** [comment]
Looks like this is not an issue and can be closed.
