### ISSUE TITLE
databases.yml add extensions to database

### ISSUE THREAD

**Issue by braampje** [ANXS/postgresql#255]
In the databases.yml file I see a lot of extensions that are added to the databases with a when condition based on item.extension name. for example item.gis. Where are these item.gis defined? I can't find this anywhere else in the role. It might just be that my limited understanding of the item.* variable is making me lost here. thank you!

UPDATE: The real problem is that I get the error message "unable to connect to database: FATAL:  database \"[{'owner': 'postgres', 'name': 'power'}]\" does not exist\n"}
While I can connect to it in PGadmin.  Am I doing anything wrong here?

I'm now running:
- name: PostgreSQL | Add extensions to the databases
  become: yes
  become_user: "{{postgresql_admin_user}}"
  postgresql_ext:
    name: postgis
    db: "{{postgresql_databases}}"
  when: postgresql_databases|length > 0

---

postgresql_version: 9.6

postgresql_databases:
  - name: power
    owner: postgres
    

postgresql_database_extensions:
  - name: postgis

  - name: tablefunc

postgresql_users:
  - name: bram
    pass: pass

  - name: reader

postgresql_user_privileges:
  - name: bram
    db: power

**Comment by gclough** [comment]
The travis tests in `tests/docker/group_vars/postgresql.yml` tests these extensions:

```
postgresql_database_extensions:
  - db: foobar
    extensions:
    - adminpack
    - pgcrypto
    - unaccent
```

Adding extensions does work, and was changed to use the Ansible modules in #307 .  Can you re-check that it's still broken?

**Comment by gclough** [comment]
@braampje , I'm pretty sure this works... but if you still have problems then please re-open this issue.
