### ISSUE TITLE
postgis.yml doesn't include yum / RedHat variation

### ISSUE THREAD

**Issue by mptardy** [ANXS/postgresql#258]

**Comment by erdenezul** [comment]
could I take this?

**Comment by erdenezul** [comment]
To Reproduce this error:
<pre>
$ ansible-playbook tests/playbook.yml -i vagrant-inventory
</pre>
tests/vars.yml
<pre>
---

postgresql_version: 9.6
postgresql_ext_install_postgis: yes
</pre>
VagrantFile:
<pre>
machine.vm.box = "bento/centos-6.6"
</pre>

Error output:
<pre>
TASK [postgresql : include_vars] *********************************************************************************************************************
ok: [anxs.local] => (item=/home/erdenezul/work/postgresql/vars/../vars/empty.yml)

TASK [postgresql : PostgreSQL | Extensions | Make sure the postgis extensions are installed] *********************************************************
failed: [anxs.local] (item=[u'libgeos-c1', u'postgresql-9.6-postgis-2.1', u'postgresql-9.6-postgis-scripts']) => {"changed": false, "cmd": "apt-get update", "item": ["libgeos-c1", "postgresql-9.6-postgis-2.1", "postgresql-9.6-postgis-scripts"], "msg": "[Errno 2] No such file or directory", "rc": 2}
	to retry, use: --limit @/home/erdenezul/work/postgresql/tests/playbook.retry

PLAY RECAP *******************************************************************************************************************************************
anxs.local                 : ok=7    changed=0    unreachable=0    failed=1 
</pre>
