### ISSUE TITLE
postgresql_listen_addresses not working correctly

### ISSUE THREAD

**Issue by magick93** [ANXS/postgresql#261]
Hello

I am fairly new to ansible, so its entirely possible that I am missunderstanding something.
I am trying to set the `listening_addresses`, and specified it as below (after seeing someone use this in a issue).

```
vars:
    - postgresql_listen_addresses:
      - "*"
```

However we I viewed the postgresql.conf file this section was commented out, and it seemed the server wasnt listening on this address.

Is this var supported?
Is there a better way to achieve this?

**Comment by lhoss** [comment]
that var is used and used in template `templates/postgresql.conf-9.6.j2`:
```
listen_addresses = '{{postgresql_listen_addresses|join(',')}}'		# what IP address(es) to listen on;
					# comma-separated list of addresses;
					# defaults to 'localhost'; use '*' for all
					# (change requires restart)
```

your choice makes sense and should result in:
listen_addresses = '*'

**Comment by magick93** [comment]
Thanks
