### ISSUE TITLE
I have difficult to customize data directory with my own @centos 6.8

### ISSUE THREAD

**Issue by JoshuaChi** [ANXS/postgresql#265]
I am running it under CENTOS 6.8.

My configuration:

> postgresql_data_directory: "/mnt/postgresql/data"  

ps aux | grep postgre

> postgres  3728  0.0  0.0 326016 14680 ?        S    21:43   0:00 /usr/pgsql-9.3/bin/postmaster -p 5432 -D /var/lib/pgsql/9.3/data

So the my data folder never been used.

I also found a strange configure:
```

--- a/roles/postgresql/templates/etc_systemd_system_postgresql.service.d_custom.conf.j2
+++ b/roles/postgresql/templates/etc_systemd_system_postgresql.service.d_custom.conf.j2
@@ -5,7 +5,7 @@
 User={{ postgresql_service_user }}
 Group={{ postgresql_service_group }}

-Environment=PGDATA={{ postgresql_conf_directory }}
+Environment=PGDATA={{ postgresql_data_directory }}

 ExecStartPre=
 ExecStartPre={{ postgresql_bin_directory }}/postgresql{{ postgresql_version_terse }}-check-db-dir {{ postgresql_data_directory }}
```

Any idea on this issue?

**Comment by merifri** [comment]
This role doesn't allow changing data directory in systems without systemd (rhel6). To change data directory, you need to change the PGDATA in `/etc/init.d/postgres` file.

As a simple solution: you can create a symlink before the installation ( `/var/lib/pgsql/ -> /mnt/postgresql/` )

**Comment by Thetortuga** [comment]
Hello,
@merifri Actually, we can't, the role is checking that the path exists and is a directory during the process. Did you managed to solve the issue this way ?

**Comment by merifri** [comment]
@Thetortuga  Of course we can. But we should not change `postgresql_data_directory` variable.

You just need to create a symlink from `/var/lib/{{ postgresql_varlib_directory_name }}` (`/var/lib/pgsql` in rhel).
Role checks the existence of the data directory ( `/var/lib/{{ postgresql_varlib_directory_name }}/{{postgresql_version}}/{{postgresql_cluster_name}}` ), not `/var/lib/{{ postgresql_varlib_directory_name }}`.

---

But this is not the best solution. The best solution is fork and fix the role 😄

**Comment by Thetortuga** [comment]
Oh, right ! Nice trick, I should have think of this ! Thanks.

**Comment by jlozadad** [comment]
can't we solve this also with a systemd file that has this changed? or template said file? Most of the deployments I seen never use the default in /var/lib/
