### ISSUE TITLE
typo in postgresql 9.6 template - synchronous_standby_names

### ISSUE THREAD

**Issue by mingxiangchan** [ANXS/postgresql#269]
there is an extra pair of brackets in line 247 in `templates/postgresql.conf-9.6.j2`

should be changed to
```
synchronous_standby_names = '{{postgresql_synchronous_standby_num_sync}}{% if postgresql_synchronous_standby_names != [] %} {{postgresql_synchronous_standby_names|join(',')}}{% endif %}'	# standby servers that provide sync rep
```

**Comment by gclough** [comment]
I ran it with the current template, and your example:

*Original* `synchronous_standby_names = '1 (host1,host2)'    # standby servers that provide sync rep`
*Prorposed* `synchronous_standby_names = '1 host1,host2' # standby servers that provide sync rep`

The Original matches the documentation, where the brackets are indeed necessary:

https://www.postgresql.org/docs/9.6/static/runtime-config-replication.html

_This parameter specifies a list of standby servers using either of the following syntaxes:_
*num_sync ( standby_name [, ...] )*
*standby_name [, ...]*

The problem arises when you  don't have the `postgresql_synchronous_standby_num_sync` variable set, that then delivers invalid syntax:

`synchronous_standby_names = ' (host1,host2)'    # standby servers that provide sync rep`
