### ISSUE TITLE
Guidence integrating TimescaleDb

### ISSUE THREAD

**Issue by magick93** [ANXS/postgresql#272]
Hello

I'm interested in adding support for https://github.com/timescale/timescaledb but have limited experience with Ansible.

Is it possible to get some guidance on how to do this? Is it even possible?

Thanks

**Comment by jlozadad** [comment]
im not sure what timescaledb can do or how much different it is from a regular postgresql install. if you can do some research and let us know the progress then we can figure out if it fits in here. for example, if you can install postgres and just add extra rpms or config to make it work then it sounds possinle.
