### ISSUE TITLE
pgsql 10.1

### ISSUE THREAD

**Issue by alter** [ANXS/postgresql#273]
Will you add support of pgsql 10.1 ?

**Comment by jlozadad** [comment]
I will have to checkout if there is a big different between current versions and 10.x

**Comment by jlozadad** [comment]
there is a PR for this https://github.com/ANXS/postgresql/pull/262 if you want to test it. I have not yet.

**Comment by Drewster727** [comment]
+1 for this. I'm about to do a cutover from 9.1... really would prefer to be on latest. Thanks!

**Comment by jlozadad** [comment]
it has been merged earlier today. closing.
