### ISSUE TITLE
"/var/lib/postgresql/10/main" data directory ?

### ISSUE THREAD

**Issue by HugoPuntos** [ANXS/postgresql#279]
Hello,

Why does the playbook automatically create a cluster in the directory "/var/lib/postgresql/10/main" ?

Thanks for your help,

**Comment by erdenezul** [comment]
You could see a following line from defaults/main.yml
<pre>
postgresql_data_directory: "/var/lib/{{ postgresql_varlib_directory_name }}/{{postgresql_version}}/{{postgresql_cluster_name}}"
</pre>
You can change this variable value when you don't want to data directory not in /var/lib/
@HugoPuntos

**Comment by erdenezul** [comment]
https://github.com/ANXS/postgresql/blob/5f42684984d81a27ff17cf94ff06f03d9d495131/defaults/main.yml#L76,#L77

**Comment by jlozadad** [comment]
you still need help with this one?
