### ISSUE TITLE
Allow use of "--xlogdir / --waldir" during initdb

### ISSUE THREAD

**Issue by gclough** [ANXS/postgresql#283]
Currently there is no way to feed the "`--xlogdir`" (<=Postgres v9.6) or "`--waldir`" (>= Postgres v10) option to `initdb`.  This is frequently used to locate the currently active WAL onto a separate filesystem, either for performance or for stability reasons.

**Comment by erdenezul** [comment]
PR #277  should do it 
Related PR: #277

**Comment by gclough** [comment]
Hi @erdenezul,

I don't think #277 fixes it, as this parameter can only be set during `initdb`.  I have some code to do this, but I need to figure out how to do a pull request in Git.  :-/

Cheers,
Greg.
