### ISSUE TITLE
HELP Wanted: I will happily help maintain

### ISSUE THREAD

**Issue by maglub** [ANXS/postgresql#285]
Hi,

I would happily hepl maintain this repo, perhaps not as a main responsible, but I would love to kick the tyres every now and then.

**Comment by gclough** [comment]
The best way I've found is to raise a specific issue, and then create a pull request with some code.

**Comment by maglub** [comment]
Works for me, will do!

**Comment by otakup0pe** [comment]
Echoing what @gclough says... Pull requests welcome! If you are willing to help with issue triage, or merge / test pull requests, then we can talk on Gitter.
