### ISSUE TITLE
Create extensions with `postgresql_ext` instead of using `psql`

### ISSUE THREAD

**Issue by gclough** [ANXS/postgresql#292]
Ansible has a native module to handle PostgreSQL extensions called `postgresql_ext`:

http://docs.ansible.com/ansible/latest/postgresql_ext_module.html

We should use that, instead of calling `shell`, which then calls `psql`.

**Comment by gclough** [comment]
I tested this on the normal extensions part, and it seems to work:

`- name: PostgreSQL | Add extensions to the databases
  postgresql_ext:
    db: "{{ item.0.db }}"
    login_user: "{{ postgresql_service_user }}"
    port: "{{ postgresql_port }}"
    name: "{{ item.1 }}"
  with_subelements:
    - "{{ postgresql_database_extensions }}"
    - extensions
  register: result`

Who can test it for the rest of the cases (hstore,postgis, etc.)

**Comment by taybin** [comment]
What's the status of this?

**Comment by gclough** [comment]
This should be closed, as it was fixed in #307.
