### ISSUE TITLE
loops & with_items

### ISSUE THREAD

**Issue by jlozadad** [ANXS/postgresql#306]
they are going to change in 2.5 https://www.ansible.com/blog/loop-plays-past-present-future so this issue is to keep track of it.

**Comment by gclough** [comment]
I'm quite new to Ansible, but this seems to make it _more_ complicated... so I'm not sure what problem they are trying to fix with this. :-/

**Comment by jlozadad** [comment]
From my understanding looks it just wording.

**Comment by gclough** [comment]
Role updated to avoid deprecation warnings.
