### ISSUE TITLE
Add support for Amazon (AWS) linux

### ISSUE THREAD

**Issue by gclough** [ANXS/postgresql#316]
We should support deployment to Amazon (AWS) linux distributions

**Comment by erdenezul** [comment]
I've used this role on aws instance(Ubuntu).

**Comment by gclough** [comment]
I've not tried it, but does it work on "Amazon Linux"?  Does it report itself to Ansible as Ubuntu?  If so, then I guess we can close this...

**Comment by erdenezul** [comment]
I've tried it on Amazon instance(Ubuntu xenial)

**Comment by UnderGreen** [comment]
```
[ec2-user ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2.0 (2017.12)"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2.0"
PRETTY_NAME="Amazon Linux 2.0 (2017.12) LTS Release Candidate"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2.0"
HOME_URL="https://amazonlinux.com/"
```
Amazon is their own system. Mostly compatible with RH 7, I hope.
