### ISSUE TITLE
addd in handler to only use service when is a system that does not have systemd

### ISSUE THREAD

**Issue by jlozadad** [ANXS/postgresql#329]
in the handlers file, service and systemd are called because in systemd, service is still available. will have to add a ```when``` is centos 6 or ubuntu 13.04 as a example. any system that uses init.d.

**Comment by gclough** [comment]
#294 should do this... but I need to figure out why it failed a single Travis test. :-/

**Comment by jlozadad** [comment]
seems like the same issue in https://github.com/ANXS/postgresql/issues/328

**Comment by gclough** [comment]
That issue is fixed by #331.  Once that's merged then I'll pull it into this change.

**Comment by gclough** [comment]
#294 is building correctly now, and I'm pretty sure this will cover what you want.  Basically I'm using "`service:`" everywhere thought, as that automatically figures out which type of command it needs to use.

I'm only using "`systemd:`" to do a `daemon-reload` after things change.

**Comment by jlozadad** [comment]
going to have to test #331 since im not sure about hsving to add the roles path to point to another handler file.

**Comment by gclough** [comment]
Sorry @jlozadad ... I think I got my issue numbers mixed up.  #331 doesn't fix it... but #294 should.

If you can advise on a better way to achieve the reload vs. restart logic, then I will be very happy to learn.  I'm only starting my Ansible journey...
