### ISSUE TITLE
Unquoted synchronous_standby_names leads to error

### ISSUE THREAD

**Issue by hakoerber** [ANXS/postgresql#337]
Hi!

I'm using this module with a specific host list in ``synchronous_standby_names``. The template renders like this:

```
synchronous_standby_names = 'ANY 1 (postgres-slave01.example.com,postgres-slave02.example.com)'
```

Because the hosts include a dash (``-``), this leads to a PostgreSQL startup error:

```
2018-04-09 14:41:33.522 GMT [12094] LOG:  invalid value for parameter "synchronous_standby_names": "ANY 1 (postgres-slave01.example.com, postgres-slave02.example.com)"
2018-04-09 14:41:33.522 GMT [12094] DETAIL:  syntax error at or near "-"
2018-04-09 14:41:33.523 UTC [12094] FATAL:  configuration file "/etc/postgresql/10/main/postgresql.conf" contains errors
pg_ctl: could not start server
Examine the log output.
```

The host names have to be quoted with double quotes according to https://www.postgresql.org/docs/10/static/runtime-config-replication.html#GUC-SYNCHRONOUS-STANDBY-NAMES

I already fixed it and will open a pull request ASAP.

**Comment by gclough** [comment]
@hakoerber ... how are you getting the "ANY 1" at the front of your `synchronous_standby_names` string?

I wrote PR #300 to Fix #269... and I put some code in there to handle the <= v9.5, v9.6, and >= v10 conditions.  This change makes sense, but I don't know how/if we should merge these two?

Maybe @jlozadad or @UnderGreen can advise...

**Comment by hakoerber** [comment]
About the "ANY 1": I kind of cheated and used ``postgresql_synchronous_standby_num_sync``. My Ansible variables look like this:

```yaml
postgresql_synchronous_standby_num_sync: "ANY 1"
postgresql_synchronous_standby_names:
  - postgres-slave01.example.com
  - postgres-slave02.example.com
```

I am not sure how to get this in sync with #300, my guess would be to merge your pull request first and then mine. Mine is not ready to merge anyway until we agree on way to handle v<10.

**Comment by gclough** [comment]
@hakoerber, I'm pretty sure I've covered all situations in #300 , with the introduction of a new parameter into `defaults/main.yml`:

```
postgresql_synchronous_standby_choose_sync: "FIRST" # >= 10
```

These are then used in the various `templates/postgresql*j2` files to assemble them in the correct way, for all versions of PostgreSQL.  I've included your extra quotes, so all hostnames should now be quoted in all circumstances.

If you could test/verify that PR, then maybe it will accepted to merge.

**Comment by hakoerber** [comment]
I do not want to be pedantic, but I think it's questionable to incorporate changes from another merge request into your merge request without attribution. I have no idea how this is usually done. Might have been better to cherry-pick my commit on top of your branch. 

Anyway, I do not want to make a fuss about it. I will look into #300 as soon as I got time.

**Comment by gclough** [comment]
@hakoerber ... sure, and I don't want to steal any credit, but I had made some pretty wholesale changes to the way this parameter was generated... so I figured it was easiest to move the quoting part into it.  Is there any way to rebase your changes on top of #300?  If not, then how can I give attribution correctly?
