### ISSUE TITLE
Locale generation requires restart, otherwise SQL commands fail

### ISSUE THREAD

**Issue by hakoerber** [ANXS/postgresql#342]
When the locale is not present when the role is run, it is generated, as required. The problem is that postgresql is not restarted afterwards, which makes subsequent commands like `CREATE TABLE` fail with a locale error.

This issue is not yet actionable, I will gather more information as soon as I can.

**Comment by gclough** [comment]
@hakoerber, I've messed with the restart/reload mechanism in #294, but it's not been merged yet.  Unfortunately the advice was to push all restart/reloads into handlers, which will only fire at the end.

If you're wanting to do a restart in the middle of the play, then you'll have to do it manually like in #331... but I've tried to introduce the concept in #294 that we should **_only_** restart when the `postgresql_restart_on_config_change` parameter is `true`... and I can see why you would want to force a restart, but then it becomes a question of whether we honour the requirement to have this locale change and restart the cluster... or honour the "create no downtime unless instructed" ethos I've tried to use in #294.

Can you provide an example of exactly what you're doing, and the error?

**Comment by hakoerber** [comment]
Hey sorry, looks like I lost track of this.

I think this can be closed.
