### ISSUE TITLE
how to change default/main.yml ? 

### ISSUE THREAD

**Issue by learnbybit** [ANXS/postgresql#357]
hi how to change default/main.yml ?

**Comment by gclough** [comment]
Use `vi`, or your favourite editor.  Probably you're better off using `group_vars` or `host_vars`, which are basic Ansible concepts.  Here's a good book:

https://www.amazon.co.uk/Ansible-Up-Running-Lorin-Hochstein/dp/1491979801/ref=sr_1_1?ie=UTF8&qid=1525166129&sr=8-1&keywords=ansible+up+and+running&dpID=517gIkgx2SL&preST=_SX258_BO1,204,203,200_QL70_&dpSrc=srch

**Comment by UnderGreen** [comment]
@learnbybit Please read [User Guide](http://docs.ansible.com/ansible/latest/user_guide/index.html) first.
