### ISSUE TITLE
Allow WAL data to be stored in a different location

### ISSUE THREAD

**Issue by timorjim** [ANXS/postgresql#358]
Feature request:
Having the WAL data on a different disk to the rest of the data can be beneficial. It would be great if you supported setting the data directory and the WAL directory.

https://www.postgresql.org/docs/10/static/wal-internals.html

Thanks

**Comment by gclough** [comment]
This was fixed in #287 ... but I'm not sure if it's a part of a numbered release yet.  At a minimum it's been merged into the master branch.

Check that out and see if it's working for you @timorjim, and if not, please let me know.

**Comment by gclough** [comment]
Closing. Fixed by #287
