### ISSUE TITLE
Ubuntu 14.04 does not come with en_US.UTF-8 locale

### ISSUE THREAD

**Issue by do3cc** [ANXS/postgresql#37]
I've changed the locales to C.UTF-8, which exists in Ubuntu 14.04

**Comment by miloskroulik** [comment]
This doesn't work for me on Ubuntu 14.04 Server. Error message is:

`msg: The locales you've entered is not available on your system.`

**Comment by bogomya** [comment]
@miloskroulik , I have the same problem on my Ubuntu 14.04 Server. Any solutions ?

**Comment by soupdiver** [comment]
When spinning up a VM based on the included `Vagrantfile` a get an Ubuntu 14.04 and have `en_US.UTF-8` included.

Is this still an issue for you guys?

Otherwise I would think you have to ensure that the local you're using should be present on the system.

**Comment by hrstoyanov** [comment]
When I build a fresh Ubuntu 14.04 docker image and try to install postgres, I get:
TASK: [ANXS.postgresql | PostgreSQL | Ensure the locale is generated] ********* 
failed: [localhost] => {"failed": true}
msg: /etc/locale.gen and /var/lib/locales/supported.d/local are missing. Is the package “locales” installed?


However, this variables seem to fix the problem:

...
postgresql_version: 9.4
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'

**Comment by soupdiver** [comment]
Ok so I will close this issue.
Feel free to reopen if there is something to do with the playbook itself
