### ISSUE TITLE
Helping maintenane of this role

### ISSUE THREAD

**Issue by asafo** [ANXS/postgresql#379]
Hello

I'm willing and able to help, know quite good postgres and ansible,
Using both in production, i'm going to try with this role this time.

Thanks

**Comment by otakup0pe** [comment]
Excellent! I will reach out to you and we can hash out details.

**Comment by otakup0pe** [comment]
Email sent, looking forward to collaborating!

**Comment by otakup0pe** [comment]
Hmm. I sent an email to the one on your github profile and it bounced.
