### ISSUE TITLE
Install fails because initdb hasn't run yet.

### ISSUE THREAD

**Issue by captn3m0** [ANXS/postgresql#39]
I'm still figuring out ansible, so please bear with me. At the end of the install package stage, postgres tries to start itself. However, the postgres clusters haven't been set up yet, which cause the service startup to fail, which fails the entire role. Not sure why this is happening.

```
TASK: [Ansibles.postgresql | PostgreSQL | Install PostgreSQL] ***************** 
failed: [clipx.captnemo.in] => (item=postgresql-9.3,postgresql-client-9.3) => {"failed": true, "item": "postgresql-9.3,postgresql-client-9.3"}
stderr: E: Sub-process /usr/bin/dpkg returned an error code (1)

stdout: Reading package lists...
Building dependency tree...
Reading state information...
postgresql-9.3 is already the newest version.
The following packages were automatically installed and are no longer required:
  linux-backports-modules-hv-3.2.0-57-virtual libjpeg-turbo8 libjpeg8
  linux-headers-3.2.0-57 walinuxagent-data-saver libxslt1.1 nginx-full
  init-system-helpers nginx-common python-greenlet python-gevent
  linux-headers-3.2.0-57-virtual rlwrap libgd2-noxpm
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 65 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up postgresql-9.3 (9.3.5-1.pgdg12.4+1) ...
 * Starting PostgreSQL 9.3 database server                                       * The PostgreSQL server failed to start. Please check the log output.
                                                                         [fail]
invoke-rc.d: initscript postgresql, action "start" failed.
dpkg: error processing postgresql-9.3 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 postgresql-9.3

msg: 'apt-get install 'postgresql-9.3' ' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/nemo/site.retry
```

The log holds nothing useful, but on trying to force postgres to start, I get the following error:

```
postgres@epicmail-main:/mnt/postgresql/9.3/main$ /usr/lib/postgresql/9.3/bin/postgres -d 3 -D /var/lib/postgresql/9.3/main    -c config_file=/etc/postgresql/9.3/main/postgresql.conf
2014-08-07 16:41:51 UTC FATAL:  "/mnt/postgresql/9.3/main" is not a valid data directory
2014-08-07 16:41:51 UTC DETAIL:  File "/mnt/postgresql/9.3/main/PG_VERSION" is missing.
2014-08-07 16:41:51 UTC DEBUG:  shmem_exit(1): 0 callbacks to make
2014-08-07 16:41:51 UTC DEBUG:  proc_exit(1): 0 callbacks to make
2014-08-07 16:41:51 UTC DEBUG:  exit(1)
```

which tells me that initdb hasn't been called yet. This is on Ubuntu 12.04 on Azure cloud.

**Comment by soupdiver** [comment]
Is that still relevant?

**Comment by captn3m0** [comment]
I haven't used this playbook in a long time, but if I remember it correctly, it happened because I was trying to setup postgres to use a different data directory than the default.

Don't know if its still reproducible.

**Comment by skrauchenia** [comment]
@soupdiver  It is still reproducible

**Comment by tadam** [comment]
Tried this role today. It's still reproducible in Ubuntu Xenial if `postgresql_data_directory` is different from default (don't know what happens if the default parameter is used).

As I understand the problem is in `tasks/configure.yml`. The task with `initdb` named `PostgreSQL | Initialize the database | RedHat` is called only for RedHat-like OS.

**Comment by briandbecker** [comment]
Seems to be same issue as here https://github.com/ANXS/postgresql/issues/236

**Comment by fornof** [comment]
does this have a solution?

**Comment by jlozadad** [comment]
This can be closed since is a duplicate of #236 and you can find more info there.

**Comment by gclough** [comment]
@jlozadad, can you @UnderGreen, or @otakup0pe close these old ones... or do we have to wait for @captn3m0 to do it?

**Comment by jlozadad** [comment]
I can't close em which is why I been going to different tickets and mention they can be closed.

Jonathan Lozada De La Matta

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by captn3m0** [comment]
Just noticed this comment, closing.
