### ISSUE TITLE
PostgreSQL 11 CentOS

### ISSUE THREAD

**Issue by tasselchof** [ANXS/postgresql#398]
Repository url, that role is using, is wrong: https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-centos11-11-.noarch.rpm (must be: https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm).

**Comment by gclough** [comment]
Fixed by #405
