### ISSUE TITLE
I can help maintain this role

### ISSUE THREAD

**Issue by rbjorklin** [ANXS/postgresql#400]
As of right now there are 46 PRs wating to be merged, I'm sure not all of them are in a good state anymore but then they should be closed. My intention is to merge as many as possible of the oustanding PRs unless there are objections to doing that.

**Comment by thbar** [comment]
It would be great if all the people willing to help out could chime in here!

I'm very concerned that such a beautiful role would go unmaintained for too long, especially given the release pace of Ansible.

Happy to help out from time to time.

**Comment by gclough** [comment]
I've recently been appointed to help cleanup this role, as I have good experience with PostgreSQL and a modicum of Ansible skills.  I've done an initial pass on the outstanding PR's, closed some, and reinvigorated others.

I'll start on the issues soon, and hopefully we can get the pulse of this project back to a steady clip.

@gclough

**Comment by rbjorklin** [comment]
That's awesome @gclough! I have an internal PR that adds replication with repmgr that's waiting for approval to be open sourced which I hope can be of use to others. It would make me very happy if the PRs for Postgres 11 support could be merged soonish:tm:

**Comment by nchudleigh** [comment]
@rbjorklin @gclough Willing to help with this as well, I cannot commit to maintaining but can jump in on PRs where needed.  Let me know where I can help out.  I am big on support / validation of latest versions of Postgres (11, 10.7) and Ubuntu (18.04, 18.10)

**Comment by gclough** [comment]
Thanks @nchudleigh.  I'm trying to review/merge any good quality PR's, and close those that are old/broken and orphaned.

If you could review/comment on any PR's, then that would be very helpful.

**Comment by nchudleigh** [comment]
Awesome, should be able to take a look at a couple this week.

**Comment by nchudleigh** [comment]
@rbjorklin I have a couple PRs that could use a look if you have time.

**Comment by moshthepitt** [comment]
I'd also be willing to help maintain this role.  I use it a lot!

**Comment by gclough** [comment]
Thanks @moshthepitt .  If you could review/comment on any outstanding PR's, that would be great.  I did a pass on all of them a month ago, but I'm not sure if any should be retired, rebased, or are suitable for merge.

**Comment by maglub** [comment]
I am happy to pitch in as well. Will go through the pull requests and make some comments.

**Comment by goetzk** [comment]
Depending on the required commitment I'm willing to help maintain this role while I'm using it - which I will be for a period of time. I've subscribed to this issue so will keep an eye on it for updates.

**Comment by gclough** [comment]
Thanks @goetzk .  The first thing we would like to do is review/comment/fix any of the outstanding PR's.  There's some good stuff in there, but I've not got the time to do it justice.

If you could reach out to the author, and make sure it's:

1) Adding something worthwhile
2) Functional
3) Matches the existing coding style

If you have something you think is ready, please flag it up to me and I can merge if necessary.

**Comment by egmont1227** [comment]
This Thead continues in #498 with more up-to-date comments.

Would close this one @gclough
