### ISSUE TITLE
Does anyone know how to trigger a "Galaxy" refresh?

### ISSUE THREAD

**Issue by gclough** [ANXS/postgresql#429]
Our listing on galaxy.ansible.com is out of date, and I've no idea how to trigger it to be refreshed.  There is a new version that's not been picked up, and many commits... but presently Galaxy says that the last commit was 1 year ago. :-/

https://galaxy.ansible.com/anxs/postgresql

**Comment by maglub** [comment]
According to the Ansible Galaxy docu, it should actually have picked up your release.

* You have a tag called v1.11.0
* https://galaxy.ansible.com/docs/contributing/version.html

This thread might be close to our issue: https://github.com/ansible/galaxy/issues/1574

Perhaps "recent" changes have made the import a bit more strict, skipping versions that are prefixed with a "v".

Try and make a release and tag it 1.11.0 instead of v1.11.0.

//magnus

**Comment by maglub** [comment]
Hi again,

After browsing other projects, it seems like many of them does not have any prefix in their version number.

So, make a release named 1.11.0 instead of v1.11.0.

**Comment by gclough** [comment]
Hi @maglub,

I've tried `1.11.1`, but that didn't seem to work either:

```
Last Commit | a year ago

Last Import | 19 hours ago
```

I think I found the root cause:

`Task "415055" failed: 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}`

https://galaxy.ansible.com/my-imports?repository_name=postgresql&selected=415055&page_size=10&page=2

**Comment by gclough** [comment]
@jlozadad , @UnderGreen , @otakup0pe , can any of you fix this?

**Comment by maglub** [comment]
Godo find!

**Comment by gclough** [comment]
@jlozadad , @UnderGreen , @otakup0pe , I think we need your help here, as I've no idea the account used to configure galaxy in the first place.

**Comment by vladp** [comment]
@gclough  where you able to get in touch with @jlozadad , @UnderGreen , @otakup0pe 
WRT galaxy credentials to refresh the role?

if not, would it make sense to contact Galaxy folks to see if they can help?
Alternatively, this git repo can get renamed (if the role is to continue to live through).

**Comment by otakup0pe** [comment]
I've triggered a refresh. There is an issue I've been trying to sort out with the Travis folk affecting our ability to trigger refreshes based on merges to the mainline branch.

**Comment by otakup0pe** [comment]
@gclough let's sync up on gitter this week to get you sorted out with access to galaxy...

**Comment by gclough** [comment]
Galaxy has been refreshed.  Thanks!
