### ISSUE TITLE
There is no version v1.11 on galaxy repository

### ISSUE THREAD

**Issue by Luizm** [ANXS/postgresql#437]
Hi there.

I'm trying to install the latest version of Postgres galaxy, but in the https://galaxy.ansible.com/anxs/postgresql the last version is `v1.10.1` isted of `v1.11.1`

**Comment by gclough** [comment]
Thanks for the report, and yes, we've noticed this in #429 .  It seems that there is a credential problem that hopefully @jlozadad , @UnderGreen , or @otakup0pe can help fix.

Sorry about the confusion. :-/

**Comment by Luizm** [comment]
> we've noticed this in #429

Oh, I didn't see it. Thank you for clearing that up

**Comment by gclough** [comment]
Galaxy has no been refreshed.  Sorry about that.

**Comment by dukex** [comment]
@gclough Now the version 1.12 is not in galaxy repository
