### ISSUE TITLE
Not working on ARM

### ISSUE THREAD

**Issue by axos88** [ANXS/postgresql#44]
Hello!

Fails on ARM, due to missing packages. Is there a way to build from source?

TASK: [postgresql | PostgreSQL | Add PostgreSQL repository] *******************
failed: [7c669d537a3e] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1409504381.97-216554174396296/apt_repository", line 2207, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1409504381.97-216554174396296/apt_repository", line 430, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 418, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/wheezy-pgdg/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)
, E:Some index files failed to download. They have been ignored, or old ones used instead.

FATAL: all hosts have already failed -- aborting

**Comment by blusewang** [comment]
果断去编译！
