### ISSUE TITLE
There is no version v1.12.0 on galaxy repository

### ISSUE THREAD

**Issue by amacvar** [ANXS/postgresql#467]
Hi,
Relatively new to this, but seems that galaxy repository is missing latest v1.12.0
https://galaxy.ansible.com/anxs/postgresql

In the meanwhile (please confirm), I was able to install using this: (Thank you #227 @moviedo )

ansible-galaxy install ANXS.postgresql -r install_roles.yml --force
> cat install_roles.yml
- src: https://github.com/ANXS/postgresql
  version: v1.12.0
  name: ANXS.postgresql

**Comment by taybin** [comment]
I see this as well.

**Comment by moviedo** [comment]
I believe this issue is related to the [missing role_name property](https://github.com/ANXS/postgresql/blob/master/meta/main.yml#L4) in the meta file. Ansible galaxy [docs](https://galaxy.ansible.com/docs/contributing/importing.html#role-name-limitations) state they've deprecated the old logic of parsing the repo name for determining the role's name.

**Comment by pescobar** [comment]
if would be nice if latest release is published in galaxy

**Comment by taybin** [comment]
@amacvar 

> > cat install_roles.yml
> 
>     * src: https://github.com/ANXS/postgresql
>       version: v1.12.0
>       name: ANXS.postgresql

To be clear, the contents of this file should be:
```yaml
roles:
  - src: https://github.com/ANXS/postgresql
    version: v1.12.0
    name: ANXS.postgresql
```

**Comment by taybin** [comment]
Any update on this?

**Comment by gclough** [comment]
We have had problems with it syncing in the past.  Let me see if @otakup0pe or @jlozadad can help.  v13 should be available soon, to we will want that reflected in Galaxy as well.

**Comment by otakup0pe** [comment]
Will look into this and see whats up. At the least, can do a manual release.
