### ISSUE TITLE
Broken Mirror

### ISSUE THREAD

**Issue by Steve-Dillon** [ANXS/postgresql#497]
First of all sorry if i sound like i don't know what i'm talking about.... I ran the a playbook point at the postgresql role and hit the error detailed below. I can navigate to http://yum.postgresql.org/11/redhat/rhel-7-x86_64/repodata which redirects me to https - but "a72a4329c15e9f64d3542d135a7b33191b519832242f70cb9217b92a0807847c-primary.sqlite.bz2" is no longer available. How can i change it to look for "1d69092e5ae6b460c11933468b78808422f641f6fb7bad9318eaee35610a2110-primary.sqlite.bz2"

Error Details:
FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/a72a4329c15e9f64d3542d135a7b33191b519832242f70cb9217b92a0807847c-primary.sqlite.bz2 from postgresql: [Errno 256] No more mirrors to try.\nhttp://yum.postgresql.org/11/redhat/rhel-7-x86_64/repodata/a72a4329c15e9f64d3542d135a7b33191b519832242f70cb9217b92a0807847c-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found"}

Thanks for any help in advance it would be a major help. - Steve

**Comment by maglub** [comment]
Normally this is resolved by yum. Since we have worked quite a bit on the testing of this role, I assume that this is no longer an issue.

Please re-open this issue if you still have this issue.
