### ISSUE TITLE
how to add citext, pgcrypto, plpython?

### ISSUE THREAD

**Issue by mw44118** [ANXS/postgresql#50]
Hi -- I found the example showing how to add the uuid and hstore extensions.  Those are great.  But how would I add more extensions, like the ones I listed in the title?

**Comment by mrgamer** [comment]
+1

**Comment by soupdiver** [comment]
Currently you have to add a file to: https://github.com/ANXS/postgresql/tree/master/tasks/extensions if you have to install additional packages
and enable the extension in https://github.com/ANXS/postgresql/blob/master/tasks/databases.yml

**Comment by farridav** [comment]
Does this answer your question @mw44118 ? if so we can close this issue, or if required, update the docs to reflect this answer..

**Comment by farridav** [comment]
Closing as resolved, please feel free to re-open if you have further issues :)
