### ISSUE TITLE
Move us to travis-ci.com ASAP.

### ISSUE THREAD

**Issue by gclough** [ANXS/postgresql#502]
Our current Travis config will break in a few weeks, so can someone please move us from travis-ci.org --> travis-ci.com.

@jlozadad , @otakup0pe , or @UnderGreen ... can you help out?

![image](https://user-images.githubusercontent.com/5181715/107510968-c048d180-6b9c-11eb-9356-113782e60a57.png)

**Comment by otakup0pe** [comment]
How do we feel about github actions :eyes:

**Comment by otakup0pe** [comment]
In all seriousness, I've started the work to transition some of the lower level roles (which I actually still personally use) to molecule / GitHub Actions. At the rate I've been going at it'll be at least several weeks before it's in a state where we could leverage it in other ANXS repos.

What's the level of effort on the travis move? It's been a while since I interacted with that service.

**Comment by gclough** [comment]
@otakup0pe , I suspect we would be happy to use any CI system that you understand, and is available for free to Open Source projects.

**Comment by otakup0pe** [comment]
[build](https://travis-ci.org/github/ANXS/postgresql/builds/758415201) still seems to be happening on travis dot org

switching to the proper travis is the right thing to do in the short term. once i get an example together on a revamped [`ANXS.python`](https://github.com/ANXS/python) i'll be sure to share it.

**Comment by otakup0pe** [comment]
I have a skeleton molecule framework going under `ANXS.python`. I'll try and get that up this weekend, who is down to review it 😈

**Comment by maglub** [comment]
I am also almost done with my stuff. We should create a new branch and work on it there together.

**Comment by maglub** [comment]
For me, travis or github actions is no big change. I don't mind either.

I have gotten the molecule for postgresql to run well for Ubuntu and CentOS (<8) using Geerlingguy's containers in .travis.yml, probably making a separate branch for that to make a pull request to later today.

**Comment by otakup0pe** [comment]
> We should create a new branch and work on it there together.

Yeah I'm expecting that to be the end result. Given that the `ANXS.postgresql` role is the most popular, we should continue focusing there. Looking forward to seeing your PR!

**Comment by UnderGreen** [comment]
I am working on move some of my personal roles to molecule as well. Will be happy to help here with review when you are ready.

**Comment by maglub** [comment]
I have a PR ready now, covering all but CentOS8 for now. https://github.com/ANXS/postgresql/pull/510

We can migrate from Travis CI to github actions later this week, or to Travis-ci.com

**Comment by maglub** [comment]
It seems like the migration will be seamless, and just "happen" at some point, unless we are using protected branches.

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

Perhaps we can force it to happen earlier.

**Comment by maglub** [comment]
We have migrated the repo to github actions already.
