### ISSUE TITLE
ansible_distribution_release is undefined

### ISSUE THREAD

**Issue by pashinin** [ANXS/postgresql#51]
Have this error on Ubuntu server 14.04

```
TASK: [ANXS.postgresql | PostgreSQL | Add PostgreSQL repository] ************** 
fatal: [] => One or more undefined variables: 'ansible_distribution_release' is undefined
```

**Comment by DblD** [comment]
Care to share resolution to this @pashinin

**Comment by pashinin** [comment]
It was a long time ago. But check this output
```
ansible -m setup localhost | grep ansible_distribution_release
        "ansible_distribution_release": "trusty",
```

I dont remember why you can have no such variable. Perhaps it's not Ubuntu or smth.

**Comment by DblD** [comment]
thx @pashinin, that var is set as far as I can see, different older version of Ubuntu LTS but still .....
 
ansible -m setup localhost | grep ansible_distribution_release
        "ansible_distribution_release": "precise",

**Comment by pashinin** [comment]
Get it. I think I forgot "gather_facts: yes" in my playbook

**Comment by DblD** [comment]
spot on @pashinin, "gather_facts: yes" was the trick for me too.. thx :+1:

**Comment by fiunchinho** [comment]
:+1:

**Comment by sivaprasadreddy** [comment]
"gather_facts: yes" solved the issue for me.. thanks 👍
