### ISSUE TITLE
when select (fn_return_record()).* is called, fn_return_record is executed repeatedly

### ISSUE THREAD

**Issue by zhangtianxiao** [ANXS/postgresql#512]
but,
select * from fn_return_record(), without **(record).***, it executed only once.
why?

Thanks in advance!

**Comment by maglub** [comment]
Dear zhangtianxiao,

I think you are asking your question in the wrong place. You are asking a database specific question in a repo that deals with the installation. This repository is in no way affiliated with the development of Postgresql itself.

I advice you to find the proper support forum for Postgresql and ask your question there.

I will close this ticket. Have a nice day!
