### ISSUE TITLE
Wrong postgresql_yum_repository_baseurl

### ISSUE THREAD

**Issue by JorisVanEijden** [ANXS/postgresql#514]
In `defaults/main.yml`:

postgresql_yum_repository_baseurl: "{{ postgresql_`yum`_repository_url }}/{{ postgresql_version }}/{{ ansible_os_family | lower }}/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"

has to be:

postgresql_yum_repository_baseurl: "{{ postgresql_`pgdg`_repository_url }}/{{ postgresql_version }}/{{ ansible_os_family | lower }}/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"

**Comment by maglub** [comment]
Hi @JorisVanEijden,

Could you please give a little more context to why? If I can reproduce your issue, it is easier for me to help.

* Are the installed packages wrong?
* Are you on CentOS7 or CentOS8?
* Are you on Fedora?
* Which Postgres version are you on?
* Do you have any error messages?

I am not a CentOS guy myself, but the CI/CD tests are going through properly for both 7 and 8.

The variables you are speaking of are:

```
ANXS.postgresql/defaults/main.yml:postgresql_yum_repository_url: "http://yum.postgresql.org"
ANXS.postgresql/defaults/main.yml:postgresql_pgdg_repository_url: "https://download.postgresql.org/pub/repos/yum/"
```

**Comment by JorisVanEijden** [comment]
- CentOS 7
- Postgresql 13
- Error: "No package postgresql13-server available"
- Workaround I'm using in my playbook:
```
vars:
    - postgresql_yum_repository_baseurl: "{{ postgresql_pgdg_repository_url }}/{{ postgresql_version }}/{{ ansible_os_family | lower }}/rhel-$releasever-$basearch"
```

I tested again and now it appears to work without the workaround in place.

I see `http://yum.postgresql.org/13/redhat/rhel-7-x86_64/` redirects to `https://download.postgresql.org/pub/repos/yum/13/redhat/rhel-7-x86_64/`
So I can imagine:
- the redirect was not working on the postgres website.
- our dns had trouble resolving yum.postgres.sql but not download.postgresql.org
- a setting somewhere disallowed http urls but allowed https urls
- it was not the url but something else that coincidentally got resolved at the same time I tried my workaround

I'll close this for now and will keep an eye out when I provision more new machines.

**Comment by maglub** [comment]
Great, thanks a lot!
