### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [ANXS/postgresql#517]
Hello, is new release planned? Last release was in 2019. There are lot of unreleased commits in master.

**Comment by maglub** [comment]
Hi,

This is a very good "finding", we migrated from Travis CI to Github Actions recently, and I think that the integration with Ansible Galaxy is missing.

**Comment by ajweitz** [comment]
Is there a workaround for using this role without galaxy?

**Comment by maglub** [comment]
Easy:

```
$ cat requirements.yml
...
- src: git+https://github.com/ANXS/postgresql.git
  version: master
  name: ANXS.postgresql

$ ansible-galaxy role install -f -r requirements.yml ANXS.postgresql
```
