### ISSUE TITLE
Postgis not working.

### ISSUE THREAD

**Issue by jdeg** [ANXS/postgresql#518]
I installed successfully Postgres (Centos 8 and Debian 9), but I was not able to install Postgis. Have someone tried to install it?

I tried with several Postgres versions, but none of them worked. In order to enable Postgis I only updated this variable 

`postgresql_ext_install_postgis: true`

But not sure if there are any other configuration I have to make. After the installation I created a database and ran the query

`CREATE EXTENSION postgis;`

and got this message

`SQL Error [58P01]: ERROR: could not open extension control file "/usr/pgsql-13/share/extension/postgis.control": No such file or directory
`

Even running this query 

`SELECT PostGIS_version();`

Throws me an error. What other changes should I make to run Postgis?

**Comment by ZhukovAlexey** [comment]
Check if postgis packages was installed by the role

`apt list --installed | grep postgis`

if no then check Ansible logs for task with name _name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | Debian_
