### ISSUE TITLE
Release new version to ansible galaxy 

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [ANXS/postgresql#526]
Checking this repo readme and code vs what is installed from ansible-galaxy is very different.

Currently the version in ansible galaxy is 1.11.1 which is quite outdated and doesn't support new postgres versions like 12 and 13 which was quite confusing for me until I noticed master is way ahead of any tagged release.

Is there a reason behind this?

**Comment by otakup0pe** [comment]
The reason is that life sometimes happens and people move away / towards open source projects. For a bit more context, check out [this post](https://github.com/orgs/ANXS/discussions/1). I'll see if I can get a new version uploaded to galaxy later this week 💖

**Comment by otakup0pe** [comment]
New release should be up on galaxy. The [fedora build](https://github.com/ANXS/postgresql/actions/runs/3662679597/jobs/6191955091) seemed to fail tho.
