### ISSUE TITLE
PostgreSQL 15 support?

### ISSUE THREAD

**Issue by VladDm93** [ANXS/postgresql#531]
I assume this repo is no longer maintained?

**Comment by VladDm93** [comment]
anyway will add support here 
https://github.com/VladDm93/postgresql/tree/postgres-14-15-support

**Comment by maglub** [comment]
Not abandoned, just maintained by unpaid volunteers.Please create a pull request when you have implemented pg15 in your fork. Would be lovely!//magnus Sent from my iPhoneOn 5 Nov 2022, at 23:40, Dmitriev Vlad ***@***.***> wrote:﻿
anyway will add support here
https://github.com/VladDm93/postgresql/tree/postgres-14-15-support

**Comment by otakup0pe** [comment]
> Not abandoned, just maintained by unpaid volunteers.Please create a pull request when you have implemented pg15 in your fork. Would be lovely!//magnus Sent from my iPhoneOn 5 Nov 2022, at 23:40, Dmitriev Vlad ***@***.***> wrote:﻿ anyway will add support here https://github.com/VladDm93/postgresql/tree/postgres-14-15-support —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

This is the answer ✨ 

For a bit more context, check out [this post](https://github.com/orgs/ANXS/discussions/1)

**Comment by gclough** [comment]
@VladDm93 , if you have the code, then please submit a Pull Request.  If not, I'll try to get it done tomorrow, after I get the 14 Pull Request to merge.

**Comment by bleetube** [comment]
I've been using the dev branch to deploy PG15 for a few weeks. Now that it has been merged in v1.14.1, I think this issue can be closed.

**Comment by MrMegaNova** [comment]
PG 15 is supported on latest version
