### ISSUE TITLE
Help Wanted!

### ISSUE THREAD

**Issue by Riccardo1976** [ANXS/postgresql#537]
Hi,

Im an RHCE8 engineer. Have had experience with Ansible for a long time (since 1.8). Am however a novice when it comes CI/CD and testing.

If i can help in any way, please let me know.

Lets get this ball rolling :)

Riccardo

**Comment by otakup0pe** [comment]
Excited for your interest! I'll let the @ANXS/postgresql team let you know what can be done to help.

**Comment by MrMegaNova** [comment]
I @Riccardo1976 , thanks for your interest in this project.
We are working on cleaning some issues and PR.

But feel free to improve some PR and create issue about feature or fix that can be usefull.
