### ISSUE TITLE
Latest Version (v1.15.0) Not Reflected in ansible-galaxy for anxs.postgresql

### ISSUE THREAD

**Issue by zarinbal** [ANXS/postgresql#557]
### Issue Description

I attempted to install version 1.15.0 of the `anxs.postgresql` role using the command `ansible-galaxy install anxs.postgresql`. However, the installation process installed version 1.13.0 instead. It seems that the latest version information is not reflecting accurately on Ansible Galaxy.

#### Steps to Reproduce

1. Execute the command: `ansible-galaxy install anxs.postgresql`

#### Expected Behavior

The latest version (v1.15.0) of the `anxs.postgresql` role should be installed.

#### Actual Behavior

The installation process installs version v1.13.0 of the `anxs.postgresql` role.

#### Alternative way to reproduce:
Execute `ansible-galaxy install anxs.postgresql,v1.15.0 --force`  will return "the specified version (v1.15.0) of anxs.postgresql was not found in the list of available version" 

### Workaround

As a temporary workaround, I manually added the required version to my Ansible requirements file:

```yaml
roles:
  - name: "anxs.postgresql"
    version: v1.15.0
    src: https://github.com/ANXS/postgresql
```

Execute the following command to install the correct version:
`ansible-galaxy install -r requirements-ansible.yaml`

### Additional Information

    Ansible Version: 2.16.2
    Operating System: Ubuntu 22.04

Note: Please investigate and update the Ansible Galaxy repository to ensure that the latest version information accurately reflects version 1.15.0 of the anxs.postgresql role.

Thank you for your attention to this matter.

**Comment by MrMegaNova** [comment]
Thanks for your report.
We are currently seeking access to upload newer versions of the role.

**Comment by MrMegaNova** [comment]
> Ohhhh. I can look into this over the next week or so. Will be taking a look across all the ANXS roles, and will prioritize this one.

Hi @otakup0pe , I've send you a message about this subject on linkedIn some days ago. Maybe we can exchange about this to synchronize our actions.

**Comment by MrMegaNova** [comment]
Hi @otakup0pe,
I hope your going well and happy new year!
As you've probably seen, we've done a lot of work on the anxs.postgresql repository.
We need access to galaxy namespace anxs to publish new release.
Can you grant me access to  the anxs namespace https://galaxy.ansible.com/ui/namespaces/anxs/
I will also need access to the anxs.postgresql project secrets to store the API key to automate the process with github action.
Thanks for your time,

**Comment by MrMegaNova** [comment]
Problem solved, we are now in sync between our git repository and ansible-galaxy
