### ISSUE TITLE
Postgresql 11 is unavailable since 2023-01-05

### ISSUE THREAD

**Issue by bbaassssiiee** [ANXS/postgresql#566]
Postgresql 11 is unavailable since 2023-01-05
https://www.postgresql.org/download/linux/redhat/

**Comment by MrMegaNova** [comment]
Hi, Thanks for your report !
We've chose to drop testing on postgresql

**Comment by MrMegaNova** [comment]
Hi,
This issue is fixed in development branch and will be merged this week in master
#567
