### ISSUE TITLE
Creating/Managing Databases on remote Host

### ISSUE THREAD

**Issue by farridav** [ANXS/postgresql#58]
Hi, 

I would like to use this role for managing my DB'S (In fact I already am), but we have recently moved our DB's to a dedicated server, In order to keep using this role I need to ensure my databases are created on a remote host, but the option is not available [here](https://github.com/ANXS/postgresql/blob/master/tasks/databases.yml#L9), Any chance we can add the `login_host` parameter [# See Ansible docs](http://docs.ansible.com/postgresql_db_module.html) just like you do with users and priveledges?

Thanks in advance, and thanks for the great work, You've made amazing contributions to the ansible community, keep it up :)

**Comment by pjan** [comment]
Hi @farridav. Been merging a lot of PRs on this one. I would happily accept a PR for this.

**Comment by soupdiver** [comment]
@farridav Anything new here?

**Comment by farridav** [comment]
nothing yet @soupdiver at my place we have our own hacked together postgres role, and are keen to move to ANXS.postgresql, but we would need to add some stuff for dealing with remote DB's

**Comment by lhoss** [comment]
I'm also interested to get this fixed!

I'ld need this mostly for managing users, dbs, so the first thing I need is to add login_host,login_user(,login_password) to: users.yml, databases.yml and users_privileges.yml task includes.

IMO defining the remote host once is the best solution, alternatively the 'host' could be given per (user)item, as done in https://github.com/ANXS/postgresql/pull/134
> login_host: "{{item.host | default(omit)}}"

Or to allow full flexibility, a combination, like following (assuming our remote host defined in new var `postgres_host` )
> login_host: "{{item.host | postgres_host | default(omit)}}"

any suggestions? 
where else to add remote support?

**Comment by lhoss** [comment]
@pjan @farridav still interested in solving this? Note I proposed a working PR 5month ago, but didn't get merged.
I'ld be happy to hear any alternative solutions and/or proposals to also support managing the postgres configs on a 'remote host' which doesn't allow for direct service restarts (like with postgres in docker)

**Comment by jlozadad** [comment]
This can be closed since this is not an issue anymore.
