### ISSUE TITLE
Support for several versions of PostgreSQL?

### ISSUE THREAD

**Issue by sebalix** [ANXS/postgresql#68]
Hi @pjan, and thanks for your work on this role!
I would like to know if it is planned to support multiple version of PostgreSQL or only the last one?
There is some issues/PR related to (#21, #47, #66)

We are maintaining several PostgreSQL versions on several Debian or Ubuntu releases, and such support would be greatly appreciated. And of course, I'm ready to contribute a lot for this purpose.
Have you stated anything about this, or experienced trouble regarding such support?

Regards,

**Comment by clonedagain** [comment]
Since the role uses the deb packages provided by the upstream Postgres team, it would make sense to be able to install all the versions they support (starting at 8.4).

**Comment by jesselang** [comment]
There's good support now for 9.x. Is that sufficient for this request?

**Comment by sebalix** [comment]
Yes, PostgreSQL is now supported from 9.1 to 9.5, closing.
