### ISSUE TITLE
User creation error - "FATAL:  the database system is starting up"

### ISSUE THREAD

**Issue by davidmcclure** [ANXS/postgresql#73]
Hello - thanks for all the work on this project! 

I've been using this role for the last couple months to deploy Postgres 9.3. Yesterday, I switched to 9.4, and now I get an error when the playbook tries to [create database users](https://github.com/ANXS/postgresql/blob/master/tasks/users.yml#L8):

```
TASK: [postgres | PostgreSQL | Make sure the PostgreSQL users are present] **** 
failed: [XX.X.XXX.XXX] => (item={'name': '****', 'pass': '****'}) => {"failed": true, "item": {"name": "****", "pass": "****"}}
msg: unable to connect to database: FATAL:  the database system is starting up
```

This comes right after a regular `service` play that checks to see if the database is running (it always is):

```
- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
```

So, it seems like there's some kind of gap between the time when the service goes up and when the database is actually ready for connections? Indeed, when I add a `pause: seconds=10` before the play in question, the problem goes away. This seems hacky, though - does anyone know what's really going on here? Thanks for any ideas!

**Comment by jlozadad** [comment]
this is not an issue anymore. closing
