### ISSUE TITLE
Issues creating db when in a virtualenv

### ISSUE THREAD

**Issue by hahnicity** [ANXS/postgresql#80]
Upon initially trying to create a postgres db I got

```
TASK: [ANXS.postgresql | PostgreSQL | Make sure the PostgreSQL users are present] *** 
failed: [127.0.0.1] => (item={'encrypted': False, 'name': 'fugazzi', 'pass': 'fugazzi'}) => {"failed": true, "item": {"encrypted": false, "name": "fugazzi", "pass": "fugazzi"}}
msg: the python psycopg2 module is required

FATAL: all hosts have already failed -- aborting
```

Which I thought was weird because this role installs python-psycopg2 on the system. Then I realized I was in a virtualenv.

```
(ansible)greg@Ithilien:~/workspace/python/ansible-playbooks$ which python
/home/greg/.virtualenvs/ansible/bin/python
```

After installing psycopg2 into my virtualenv (which requires an unincluded postgresql-server-dev-X.Y pkg) things work out just fine. Not a major problem but it does make running this role one time off the bat impossible if we want to install a db upon provisioning postgres

**Comment by hahnicity** [comment]
This leaves me with a question: Do we want to install postgresql-server-dev-X.Y with the standard install?

**Comment by jlozadad** [comment]
This can be closed. This not an issue anymore.
