### ISSUE TITLE
Change postgresql_admin_user

### ISSUE THREAD

**Issue by dylancwood** [ANXS/postgresql#82]
Has anyone had any luck using a non-standard `postgresql_admin_user`? I tried changing it to a user that exists on the remote, but it appears that many of the PG files are still owned by `postgres`, and I subsequently get the following error when creating the databases:

```
could not open relation mapping file "global/pg_filenode.map"
```

I assume that this is because the apt-get pg installation script gives ownership of everything to `postgres`. Anyone know of a way around it?

**Comment by jesselang** [comment]
I believe support for database owners is in master now.

**Comment by jlozadad** [comment]
This can be closed. Postgresql when installed creates everything under the user:group postgres. This is for security and won't be changed here.
