### ISSUE TITLE
Document adding postgis extension to DB

### ISSUE THREAD

**Issue by miloskroulik** [ANXS/postgresql#84]
Thanks for useful role! It would be useful, if adding postgis to DB could be documented on project page. Also, it would make more sense to me to name the corresponding key `postgis`, instead of just `gis`.

**Comment by soupdiver** [comment]
The variable to set is named `postgresql_ext_install_postgis ` already. Or do you mean something different?

**Comment by Igonato** [comment]
You need to run `CREATE EXTENSION postgis;` yourself to enable the extension. It would be nice if it was automated.

**Comment by Igonato** [comment]
Or rather everything on http://postgis.net/install/ in the Enabling PostGIS section.

**Comment by jlozadad** [comment]
This can be closed since this is done alrdy
