### ISSUE TITLE
Encrypted flag not used on user

### ISSUE THREAD

**Issue by storeman** [ANXS/postgresql#89]
When defining users, the `encrypted` flag is not used.

Maybe the comment should also say the password should start with `'md5'[md5pass]`

On `postgresql_user_privileges` the flag `role_attr_flags` should be moved to the `postgresql_users` because the privileges are global.

Anyhow, thanks for your effort! I'm new to ansible and it would have taken me much more time to figure everything out without your scripts.

**Comment by soupdiver** [comment]
PR is appreciated for the use of the `encrypted` flag :)
Moving the `role_attr_flags` into `postgresql_users` would be an idea but break backwards compatibility

**Comment by storeman** [comment]
PR created
