### ISSUE TITLE
[Feature request] Postgres role for Alpine Linux

### ISSUE THREAD

**Issue by hrstoyanov** [ANXS/postgresql#95]
Hi,
Is it possible to extend this role for Alpine Linux (AL)? AL is hot, ultra-minimal linux distro, ideal for cloud deployment with a nice package manager that APK, which is supported as of Ansible 2.0  module . Here are a few links:
https://github.com/fabaff/alpine-ansible
https://github.com/kiasaki/docker-alpine-postgres
http://michael.otacoo.com/postgresql-2/minimal-docker-container-postgres/

Also see: https://github.com/William-Yeh/docker-ansible/issues/2

**Comment by jlozadad** [comment]
haven't seen any updates about this. Closing.
