### ISSUE TITLE
Error, directory missing when running test.yml

### ISSUE THREAD

**Issue by roman-io** [ANXS/postgresql#97]
Vagrant 1.7.4
Virtualbox 4.3.28r100309

```
skipping: [anxs.local]
 _________________________________________________
/ TASK: PostgreSQL | Update configuration - pt. 1 \
\ (pg_hba.conf)                                   /
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [anxs.local] => {"failed": true}
msg: Destination directory /etc/postgresql/9.3/main does not exist

FATAL: all hosts have already failed -- aborting
```

**Comment by KrunoKnego** [comment]
I have the same problem. Thought it was just me doing something wrong.

**Comment by roman-io** [comment]
The issue created by locales sent via ssh connection.
On your host comment out `SendEnv LANG LC_*` in `/etc/ssh/ssh_config`
**or**
on the guest machine add 
```
export LANG=en_US
export LC_ALL=en_US.UTF-8
```
in `/etc/bash.bashrc` to apply this rule on all users.

**Comment by soupdiver** [comment]
Can't reproduce this on my system (OSX with iTerm)

Is this still a problem?

**Comment by farridav** [comment]
Also unable to reproduce on lubuntu with LXTerminal .. though I do remember having to add [this line](https://github.com/ANXS/postgresql/blob/master/.travis.yml#L12) in to get travis builds working .. though if its to do with values sent in the SSH connection its probably unrelated.. @hrstoyanov seems to have a way to reproduce using docker in https://github.com/ANXS/postgresql/issues/108 .. but not yet had time to try and reproduce..

**Comment by hrstoyanov** [comment]
@farridav, see this
https://github.com/hw-cookbooks/postgresql/issues/108
```
Problem is caused by locale settings (PostgreSQL initdb cannot init cluster because of locale settings misconfiguration or locales were set within same ssh session and weren't reloaded). Once you set proper LANG variable, recipe will work with no problem. You can do it by putting line like this just before including postgresql::server recipe :
```

**Comment by farridav** [comment]
cool @hrstoyanov will read now

**Comment by hrstoyanov** [comment]
@farridav,
When you check out this Chef thread: https://github.com/hw-cookbooks/postgresql/issues/147
it sounds like Derbian apt Postgres cluster installation fails when the locales are not set up in some strange way.  Seems like corner cases error in the apt perl script. This is why it is hard to reproduce, but with the Docker file you should see the issue easily. Also, notice that SSH can override some env variables.

Is there any way to skip the cluster configuration with this role? I do not need it anyway and it is causing the issue.

Thanks.

**Comment by roman-io** [comment]
set your host's locales for example to Hebrew-Israel `he_IL.UTF-8`, then try to reproduce the issue. This happens also with other locales, but I don't have any specific list. The host's ssh client sends locales to the guest machine, so the guest machine will be configured to the same locale. But for some reason guest machine is not aware of some unique locales and it raises that error.

**Comment by jlozadad** [comment]
is this still an issue?
