### ISSUE TITLE
No such file or directory: etc_apt_preferences.d_apt_postgresql_org_pub_repos_apt.pref.j2

### ISSUE THREAD

**Issue by restalax** [ANXS/postgresql#99]
Hello
I've been using task and get error:
TASK [ANXS.postgresql : PostgreSQL | Add PostgreSQL repository preferences] ****
fatal: [192.168.56.10]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'etc_apt_preferences.d_apt_postgresql_org_pub_repos_apt.pref.j2'"}

my meta file:
dependencies:
- role: ANXS.postgresql
  postgresql_version: '9.3'
  postgresql_encoding: 'UTF-8'
  postgresql_locale: 'ru_RU.UTF-8'
  postgresql_shared_buffers: 128MB
  postgresql_work_mem: 6MB
  postgresql_synchronous_commit: off
  postgresql_databases:
  - name: user
  - name: user_backend
    postgresql_users:
  - name: user
    pass: user
    postgresql_user_privileges:
  - name: user
    db: user
    priv: 'ALL'
  - name: user
    db: user_backend
    priv: 'ALL'
    postgresql_pg_hba_passwd_hosts: "{{ postgresql_hba_passwd_hosts }}"

**Comment by soupdiver** [comment]
can you provide the data in a more readable way and give some more information about your environment?

Also the whole log output of Ansible could help

**Comment by gclough** [comment]
This is quite old @restalax, can it be closed?
